### ISSUE TITLE
Auditing of virtual attributes (e.g. tag_list)

### ISSUE THREAD

**Issue by ledermann** [collectiveidea/audited#1]
I would like to audit virtual attributes, which are not stored as columns in the same table. Think about a “tag_list” managed by acts_as_taggable_on. This virtual attributes are stored elsewhere, but the changes should be audited in the owner model.

Perhaps this could be configured by an additional option like :add in addition to :except.

**Comment by tquill** [comment]
Got acts_as_taggable working correctly with this the after_audit callback like this:

```
def around_audit
  current_audit = yield
  if current_audit.audited_changes.has_key?("tag_list")
    current_audit.audited_changes["tag_list"][1] = self.tag_list
    current_audit.save
  end
end
```

**Comment by kayzee** [comment]
```def around_audit
  current_audit = yield

  if current_audit.audited_changes.has_key?("tag_list")
    current_audit.audited_changes["tag_list"][1] = self.tag_list.join(', ')
    current_audit.save
  end
end

**Comment by kayzee** [comment]
@tquill I found that this doesn't work with the first version of an object.
The first `audits` record will be a 'create' but it doesn't contain any associated (tag_list) values.
Subsequent `audits` records will include any changes to tag_list as planned.
```
def around_audit
  current_audit = yield
  if current_audit.action.eql?('create') && self.respond_to?('tag_list')
    current_audit.audited_changes["tag_list"] = self.tag_list.join(', ')
    current_audit.save
  elsif current_audit.audited_changes.has_key?("tag_list")
    current_audit.audited_changes["tag_list"][1] = self.tag_list.join(', ')
    current_audit.save
  end
end
```

**Comment by kayzee** [comment]
@tquill the solution you suggested is incomplete.  It only works for `self.tag_list` and does not keep track of `self.tags`.

The latter always returns the latest tags no matter what `revision` you are trying to reify.  I was playing around with adding `audited` to the Tag model, but that just saves the audit trail of each Tag.
```
class Tag < ActiveRecord::Base
  audited
end
```

**Comment by johnknapp** [comment]
@kayzee Your custom callback really helped me out. Thanks! Though I'm curious why you didn't address the update action? (For the Model I'm auditing, assigned tags change occasionally during update so I needed to add that.) Anyway cheers from 2018! (with a cc to @tquill)
