### ISSUE TITLE
README Gemfile installation instructions don't work with rc gem

### ISSUE THREAD

**Issue by gbuesing** [collectiveidea/audited#100]
The README shows the Gemfile setup as:

  gem "audited-activerecord", "~> 3.0"

Which doesn't find the gem on bundle install, because the latest version at Rubygems.org is 3.0.0.rc1.

Until 3.0 is released, the install instructions should be updated to:

  gem "audited-activerecord", "~> 3.0.0.rc1"

**Comment by kennethkalmer** [comment]
Please accept my apologies for letting this one lie idle for so long. The README has since moved on with up to date instructions.
