### ISSUE TITLE
Version number and select max() queries

### ISSUE THREAD

**Issue by kulpreet** [collectiveidea/audited#103]
It seems like you guys are using select max() to determine the version number for an audited active record.

I am a bit wary of having a select max on a log table. 

Given that the audits table could be the fattest table, the select max query could quickly become a bottle neck.

Then I looked if there was a way to disable the version tracking. I couldn't find it on the readme or in code.

I think people should be able to disable versioning and thus the dependency on the select max() query if they want to.

**Comment by kennethkalmer** [comment]
@kulpreet @SubaruWRX55 if you guys have any suggestions, please lets get ideas flowing in #189
