### ISSUE TITLE
Automatically hook `audited` into all ActiveRecord::Base classes automatically

### ISSUE THREAD

**Issue by ghost** [collectiveidea/audited#107]
Is there a way to setup or configure the Audited gem to automatically hook `audited` into every ActiveRecord::Base class automatically, like Kaminari does?  

I have a project requirement where every AR class needs to be audited, no exceptions.  It would be nice if I didn't have to manually paste "audited" into the top of every existing AR class and have to remember to do it for future classes I haven't generated yet.

**Comment by laserlemon** [comment]
I don't think we'll add this automatic configuration. It's better practice to be explicit about which models should and should not be audited. Thank you for your suggestion!
