### ISSUE TITLE
Join audits and associated_audits with a single query

### ISSUE THREAD

**Issue by zachad** [collectiveidea/audited#114]
Is it possible to join an object's audits and its associated audits into a single database query?  Right now it seems the only way to do it is by building both as arrays and combining them. It would be nice to do that in the database.  

The method now:

``` ruby
class MyObject
  audited
  has_associated_audits

  def all_audits
    (audits + associated_audits).sort_by(&:created_at)
  end
end
```

That just operates on the resulting array in memory. 

I'd rather do something like this:

``` ruby
o = MyObject.first
o.all_audits.reorder(:created_at).where(:some_other_condition)
```

Is there a way to do that now? Could it be something added to this gem?

**Comment by tquill** [comment]
I know this is old, but I'd like this too.

**Comment by BartlomiejSkwira** [comment]
Related issue: https://github.com/collectiveidea/audited/issues/117
