### ISSUE TITLE
username is nil

### ISSUE THREAD

**Issue by losingle** [collectiveidea/audited#129]
```ruby
class User < ActiveRecord::Base
  belongs_to :company
  audited :associated_with => :company
end

class Company < ActiveRecord::Base
  has_many :users
  has_associated_audits
end
```

> company.associated_audits.last.username
 => nil

but

> album.associated_audits.last.user
  User Load (0.6ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
 => #<User id: 1, username: "foo">

**Comment by kennethkalmer** [comment]
Closing this in favor of carrying on in #86
