### ISSUE TITLE
Destroying an audited model twice throws an error from audit writing

### ISSUE THREAD

**Issue by tpodom** [collectiveidea/audited#139]
If you call destroy on a model that is already destroyed the before_destroy callbacks get executed a second time and Auditor attempts to write an audit.  However, ActiveRecord throws an error because the auditable is not saved.

ActiveRecord::RecordNotSaved: You cannot call create unless the parent is saved

**Comment by aripollak** [comment]
I think this is fixed after #168?

**Comment by tbrisker** [comment]
Looks like it. Closing this issue for now, feel free to reopen if it occurs again.
