### ISSUE TITLE
without_auditing reset logic not ensured

### ISSUE THREAD

**Issue by elliottjf** [collectiveidea/audited#144]
Looking at the without_auditing method in auditor.rb, it appears that auditing will be left disabled if an exception is thrown from the block

**Comment by rrundzans** [comment]
By looking at latest code it seems that reset logic is added, but still not thread safe :(

**Comment by Stex** [comment]
Both the reset logic and the thread safety seem to be implemented to:

```ruby
# auditor.rb
def auditing_enabled
  Audited.store.fetch("#{table_name}_auditing_enabled", true)
end

def auditing_enabled=(val)
  Audited.store["#{table_name}_auditing_enabled"] = val
end
```

I guess this issue can be closed.

**Comment by domcleal** [comment]
Thanks for confirming, it looks like it was made thread-safe in a17f20d and exception-safe in c68d693.
