### ISSUE TITLE
Audit multiple current_user

### ISSUE THREAD

**Issue by thiagofm** [collectiveidea/audited#147]
Let's say I have 2 models that authenticate in my app: staff and user.

How do I set audited to work with both?

If not possible, can I refactor audited to do it? I really need it.

**Comment by kennethkalmer** [comment]
Woah, this waited very long, and I'm sorry for that!

Another suggestion is that you leverage the fact that you can set a _string_ to be used as the username during audits:

```ruby
# Initializer
Audited.current_user_method = :audited_user

class ApplicationController < ActionController::Base
  # ...
  def audited_user
    # Can return any string that you could use to identify staff or client later on.
    logged_in_as_staff? ? staff.email : client.email
  end
end
```
