### ISSUE TITLE
Different values in database and audits

### ISSUE THREAD

**Issue by tejasbubane** [collectiveidea/audited#159]
I am facing a wierd problem. Some values in my audits are different from those in the actual database table.
eg. I have a
hashed_password=8470adf9b343e9c14c6e370ce5e52babd3b1eaa1
in my Users table but in audits table it shows
hashed_password: !binary |-
  ODQ3MGFkZjliMzQzZTljMTRjNmUzNzBjZTVlNTJiYWJkM2IxZWFhMQ==

This is problematic when I display the audits in my admin panel.
What is the reason for such behaviour? And is there any way to convert back the value?

PS: This happens for each and every password, but almost all other things seem to be working fine.

**Comment by kennethkalmer** [comment]
@tejasbubane apologies for letting this one hang around. Did you ever find the cause of this issue? This gem does no encoding/decoding of the attributes. It takes the _changes_ directly from ActiveModel and stuffs it into the _audited_changes_ attribute of the audit model. Maybe another gem altered the behavior somehow?

**Comment by tejasbubane** [comment]
No. The audits table is not being particularly used in my project now so I did not find the cause.

**Comment by kennethkalmer** [comment]
@tejasbubane I'm completely stumped, I'm sorry I can't offer more insight or help here. We don't touch the attributes at all. Like I said, we simply [get the data](https://github.com/collectiveidea/audited/blob/7ac7c9f25fc5e6199bcfad6aea774547ef3ed38a/lib/audited/auditor.rb#L167-L172) from [ActiveModel::Dirty#changed_attributes](http://api.rubyonrails.org/classes/ActiveModel/Dirty.html#method-i-changed_attributes) without further processing.

If you could help us with a reproducible gist of the issue I would be so grateful. Please feel free to reopen then.
