### ISSUE TITLE
Globally disable auditing

### ISSUE THREAD

**Issue by enriquez** [collectiveidea/audited#18]
There are cases where we don't want to audit while testing, running migrations, etc...  There needs to be a way to turn auditing off and on.

**Comment by ares** [comment]
It seems the label 2.0.x is no longer valid https://github.com/collectiveidea/audited/blob/master/lib/audited/auditor.rb#L82 :-) Is there any chance for this feature to get in so can avoid hacking Audited gem internals in rake tasks where we don't won't it to audit changes?

**Comment by desoleary** [comment]
```ruby
Audited::Audit.audited_classes.each do |audited_class|
      audited_class.auditing_enabled = false # or `true` to enable
    end
```

works for me now

**Comment by laserlemon** [comment]
Thank you @desoleary. Looks like that solves/closes this issue! 👏

**Comment by lacco** [comment]
Looks like that this issue has been finally solved in https://github.com/collectiveidea/audited/pull/426 . Great!
