### ISSUE TITLE
Multi Tenant Scope?

### ISSUE THREAD

**Issue by magicmarkker** [collectiveidea/audited#190]
Is there a way to scope the audits to whatever multi tenant I have set up, for example, I need it to save the client_id for the current_client.id?

**Comment by jainankita90** [comment]
I used after_audit callback in my code. But audit.last in not created sometimes and after audit is called.
Here is code gist https://gist.github.com/jainankita90/80e847cccee604f56b06a713faa3bc18

Temporarily to fix this issue in my application I have added some delay before sending mail.

**Comment by jasper502** [comment]
To support acts_as_tenant I did this:

```
def after_audit
  self.audits.last.update!(account_id: self.account_id || nil)
end
```
