### ISSUE TITLE
What is the proper way to change audited_changes for existing audits?

### ISSUE THREAD

**Issue by andrewhubbs** [collectiveidea/audited#199]
What is the proper way to change audited_changes for existing audits?

My situation is that I have audits that store changes to encrypted values. I am now rotating the encryption keys and I would like to update the old audits to be decryptable with the new keys. It seems really messy and error prone to update the SQL column directly but I am not finding any helper functions to assign the `audited_changes` column directly. How should this be done?

**Comment by kennethkalmer** [comment]
You should be able to reassign the attribute directly with the new value:

```ruby
audit.audited_changes = object_encrypted_with_new_keys
```

We protect against mass-assignment, not normal assignment. And serialization is delegated to ActiveRecord's `serialize` implementation (when using ActiveRecord).

If this isn't too clear please help me understand and I'll do my best to clarify.

**Comment by andrewhubbs** [comment]
Thanks @kennethkalmer. That's exactly what I ended up doing.

**Comment by kennethkalmer** [comment]
@andrewhubbs :+1:
