### ISSUE TITLE
Enum field change

### ISSUE THREAD

**Issue by r00takaspin** [collectiveidea/audited#202]
Hello,

I have status field, that has enum type in ActiveRecord. When value of this field changes, old_value is string, but new_value is integer.
![2015-01-19 16 49 03](https://cloud.githubusercontent.com/assets/2390121/5802173/1d8ffca2-9ffb-11e4-8771-d4f7c1f73e4b.png)

Is it bug or feature?

**Comment by Marthyn** [comment]
*bump* i got the same problem :/

**Comment by Jidek** [comment]
_bump_ This problem still exists

**Comment by fatkodima** [comment]
Which versions of rails and audited are you using? I can't reproduce this issue.

**Comment by Jidek** [comment]
I was just able to reproduce again. Here are my version numbers: rails (4.2.6), audited (4.2.0).

**Steps to reproduce**:
1. Have a model with a field defined by an enum, like so:
![screen shot 2018-03-30 at 2 19 07 pm](https://user-images.githubusercontent.com/9002236/38148643-583aff84-3425-11e8-8cdb-127293da0baf.png)
2. Change that field on an audited record

**Expected Result**:
audited_changes should look like this:
![screen shot 2018-03-30 at 2 21 43 pm](https://user-images.githubusercontent.com/9002236/38148762-cced78ca-3425-11e8-8dd9-fb2162cb98f0.png)
OR like this:
![screen shot 2018-03-30 at 2 23 47 pm](https://user-images.githubusercontent.com/9002236/38148820-02aa8714-3426-11e8-9bca-5435d90348e1.png)


**Actual Result**:
audited_changes actually looks like this:
![screen shot 2018-03-30 at 2 21 08 pm](https://user-images.githubusercontent.com/9002236/38148781-d6629be2-3425-11e8-968c-f884015696b2.png)


I don't think it matters too much if the audited changes shows the keys or the values of the enum, but I would like it to be consistent between old and new.

Please let me know if you have any more questions I can help with for reproducing this issue.

**Comment by fatkodima** [comment]
@Jidek I have fixed this here https://github.com/collectiveidea/audited/pull/429
Let me know, if this works for you.

**Comment by Jidek** [comment]
I've been running into a lot of trouble trying to import the fix into my project for testing. It seems bundler won't let me use that branch as other gems have dependencies on the specific version of audited that we use. 

Do you have any advice on how to solve the dependency issues? If not I might have to just put together a quick rails demo project for testing the fix.

**Comment by fatkodima** [comment]
@Jidek In your situation, I think
> If not I might have to just put together a quick rails demo project for testing the fix.

is the way to go.

**Comment by Jidek** [comment]
@fatkodima I finally found some time to set up a demo environment and test your fix. It looks like it's working perfectly. 
Thanks for fixing this issue.
Do you have any idea when this might go onto the live version of audited?

**Comment by fatkodima** [comment]
@Jidek Nice. 
No, I have no idea.

**Comment by tbrisker** [comment]
I haven't had as much time to dedicate to the gem as I wish recently, so progress on the next release has been quite slow. There are several issues I would like to address in the 5.0 release, please see #430 for discussion of those.
