### ISSUE TITLE
why add default_scope about version ASC ?

### ISSUE THREAD

**Issue by hasyung** [collectiveidea/audited#207]
well, when i use query, the default_scope always conflict with custom scopes. So, i want authors cancel the default_scope.

**Comment by kennethkalmer** [comment]
You could use `#reorder` on the scope to change the version ordering:

```ruby
model.audits.reorder("version DESC")
```

We can't just drop this behavior immediately, we would need to figure out how to deprecate it properly. Thanks for raising this.
