### ISSUE TITLE
Auditing viewing of models (index or show)

### ISSUE THREAD

**Issue by tomprats** [collectiveidea/audited#210]
Is there currently a way to audit when a user views possibly sensitive data? If there isn't already an option to do this, then is there a way to create audits? For example just creating an audit manually on certain actions?

It looks like everything is based off of auditing changing data, but I'd like to use it for more than that.

Thanks for your help!
Tom

**Comment by danielmorrison** [comment]
That's not part of the feature set, but you could do this manually or do something that modifies the record (update a `viewed_at` column for example) and that could kick off an audit.
