### ISSUE TITLE
[More to a Upgrade] "enum" fields

### ISSUE THREAD

**Issue by fazelmk** [collectiveidea/audited#214]
I use "enum" fields (rails don't really have enums but I got a enum class with some constants). And the audit saves the numeric value that was saved in the database, but it would be better to save the description of that field.

Would be a better way to save the data as a hash. So I can get the hash and treat it before showing back to the users

**Comment by Yaroslav-F** [comment]
+1

**Comment by stephenorr** [comment]
Yep, I'd like to see this too.

**Comment by okuramasafumi** [comment]
It turned out that they get the new (changed) value with `self[attr]` (see https://github.com/collectiveidea/audited/blob/4.2-stable/lib/audited/auditor.rb#L173).
This is the same as calling `read_attribute` method, which returns an integer for an enum column.

Should we use `send` instead to get the string value of and enum column?

**Comment by fazelmk** [comment]
Last week I had to create a simplified Audit to a project. 
And I did make a method in each class I need to audit, so it returned a string with the text I liked to save in the audit.

I think it would be a good way to use some custom method that the developer can implement to audit a class. So if the class has the method implemented use it, otherwise user the current implementation.
This way you don't need to treat every possible scenario. Just let the developers customize the audited text by implementing the method.

**Comment by okuramasafumi** [comment]
@fazelmk Can't we just overwrite `audited_changes` method?

**Comment by okuramasafumi** [comment]
I tried to overwrite `audited_changes` and it worked perfectly. What I did is just changing `self[attr]` to `self.send attr`.

**Comment by prismatica** [comment]
Alternatively, you could check if the column is an enum.
`old_value = self.defined_enums.has_key?(attr) ? self.defined_enums[attr][old_value] : old_value`
