### ISSUE TITLE
Ability to change audited_changes column type to JSON format

### ISSUE THREAD

**Issue by kwent** [collectiveidea/audited#216]
Hi,

Would be nice to be able to switch `audited_changes` column to JSON format for PostgreSQL and be able to query inside this field like:

``` ruby
Audited::Adapters::ActiveRecord::Audit.where("(audited_changes->'name') IS NOT NULL")
```

Regards,

**Comment by etaiklein** [comment]
+1

**Comment by pricj004** [comment]
+1

**Comment by delusive** [comment]
+1

**Comment by delusive** [comment]
I added this functionality by adding an initializer and a custom serializer, until there is some official support.  I have tested this in my limited scope so use at own risk.

I added an initializer 
config/initializers/audited.rb
lib/audited_json_serializer.rb (by default this isn't autoloaded by default as of Rails 4ish)

https://gist.github.com/delusive/e05810019e23dd680e90

**Comment by danielmorrison** [comment]
In our office, we're playing with a version that uses `jsonb` columns with PostgreSQL. 

It actually works quite well so far. You change the `audited_changes` column to `jsonb` and simply remove [this line](https://github.com/collectiveidea/audited/blob/4.2-stable/lib/audited/adapters/active_record/audit.rb#L22) an it Just Works™.

We're going to try it out on a real app, then figure out how to package it up without breaking everything else. 

/cc @tbugai

**Comment by daveomcd** [comment]
What is the default format of the audited_changes column?  I was hoping to query/parse it for using in a "Facebook" style feed for objects, but i don't recognize the format.  I didn't want to build some customized parsing methods if something already exists...

**Comment by danielmorrison** [comment]
It uses Ruby’s built-in serialization, which uses YAML.

There’s an experimental postgres-jsonb branch that (as you’d guess) uses a jsonb column in postgres. It works, but we haven’t done the work to build a migration path yet.

**Comment by muhammet** [comment]
+1

**Comment by freemanoid** [comment]
hey @danielmorrison could you elaborate on what else should be done for this? I wanna spend some time to add this feature to audited.

**Comment by danielmorrison** [comment]
I'd like to see a version that uses jsonb on postgres, and possibly json on other DBs. 

Then the big question is how do we migrate people? The simple answer is we probably don't, instead we have a setting to keep the current behavior.

**Comment by freemanoid** [comment]
Yes, we can make it optional for now and make as a default behaviour for the next major release. Do you think it would be hard to write a migration for this? 

This can be a good start for postgres:
```
add_column :audits, :new_audit_changes, :jsonb
Audit.find_each do |audit|
  audit.new_audit_changes = audit.audit_changes
  audit.save!
end

remove_column :audits, :audit_changes
add_column :audits, :audit_changes, :jsonb

Audit.find_each do |audit|
  audit.audit_changes = audit.new_audit_changes
  audit.save!
end

remove_column :audits, :new_audit_changes
```

**Comment by danielmorrison** [comment]
There are probably some weird edge cases for migrating, but the "harder" part is just the time it would take if you have a ton of Audit records.

Maybe make the migration optional? 

I do think changing the default in a future version is good, but I'd want a way to not force the change on everyone.

**Comment by freemanoid** [comment]
We can leave an option to use `text` type and `serialized` column for back compaitibility and add an example migration.

Something like 
**4.3.0**: add option to use `jsonb` type.
**5.0.0**: use `jsonb` by default, option to use `text` type.
**6.0.0**: use `jsonb`, no option for `text`.

Hopefully we will catch possible migration edge cases before 5.0.0

**Comment by freemanoid** [comment]
Hey @danielmorrison any thoughts?

**Comment by tbugai** [comment]
@freemanoid 
@danielmorrison and I have been discussing that exact thing recently.  I would be fulling in support of a PR that included ```json```, ```jsonb```, and ```text``` as options with ```text``` being the default.

If no on else gets to this I may take a crack at it some time later this week.

**Comment by freemanoid** [comment]
@tbugai could you take a look at https://github.com/collectiveidea/audited/pull/304 ?

**Comment by acanyon** [comment]
+1

**Comment by acanyon** [comment]
YEAH!! :kiss:

Can we get a gem release and doc update please?! Such a valuable feature!

**Comment by domcleal** [comment]
Yes, I'm trying to prepare the library for release this week (which'll include an updated changelog). I added a bit of documentation in 615627f to show how to install audited with the json/jsonb support.

**Comment by karensg** [comment]
Thanks for merging. Would love to implement the jsonb functionality as well.
Do you have any advice how to migrate the data from the text column to jsonb? I have the migration file already.
```ruby
change_column :audits, :audited_changes, 'jsonb audited_changes::jsonb'
```

**Comment by freemanoid** [comment]
> Thanks for merging. Would love to implement the jsonb functionality as well.

JSONB is implemented in that PR as well.
