### ISSUE TITLE
undefined method `request_uuid' for #<Audited::Adapters::ActiveRecord::Audit

### ISSUE THREAD

**Issue by reginato** [collectiveidea/audited#225]
Hey guys i got this error when create a new object.
Im using gem 'rails', '4.2.1'

thanks

**Comment by ajmiddleton** [comment]
We're upgrading a project to rails 4.2.1 and I got a whole bunch of "undefined method request_uuid for Audit..." errors when I ran the test suite. Adding an "attr_accessor :request_uuid" to the gem source allowed the tests to pass, but after some consideration we are removing this gem from our project.

**Comment by jedschneider** [comment]
solution is to run `rails generate audited:upgrade` which adds a migration to append the `request_uuid` to the `audits` table.

**Comment by reginato** [comment]
Thanks guys, i created request_uuid migration and it is ok now..

**Comment by ajmiddleton** [comment]
Ours continued to fail after running the migration. Sorry, I should have clarified that in my post.

**Comment by reginato** [comment]
There wasn't a field request_uuid in the database I just created with a migrate

**Comment by linda-peirce** [comment]
@ajmiddleton I'm confused. Did adding attr_accessor allow test to pass or did they continue to fail?
