### ISSUE TITLE
Rails 4 ActiveRecord::RecordNotSaved when attempting to save 'audited' model

### ISSUE THREAD

**Issue by dekhaus** [collectiveidea/audited#233]
Hi

  I have a Rails 4.1.6 application that manages Items.  I added the ability to Audit Items (using this gem) and neglected to test that Items could still be created.  This app is a rails-api app (not sure if that matters) and I'm sure that adding 'audited' support broke the ability to create Items because a) I can reproduce the bug on my development system and b) when I rollback the the 'audit' mods - I can create an Item.
  
  The specific bug I'm seeing is that when an Item is saved an 'ActiveRecord::RecordNotSaved: ActiveRecord::RecordNotSaved' exception is thrown so the 'save' is ROLLBACKed.  The 'model' has no errors (i.e. @item.errors.full_messages -> [])
  
  As a Rails 4 app - strong parameters are being used.
  
  I tried using 'save_without_auditing' - but that doesn't work (in that the Item still doesn't save).
  
  Any help fixing this would be greatly appreciated.
  
Thanks
Dave

**Comment by dekhaus** [comment]
Solved - user error.

**Comment by fredkelly** [comment]
@dekhaus can you share your solution? Seeing a similar thing after updating attributes on a model and calling save.
