### ISSUE TITLE
Could not find generator 'audited:install'

### ISSUE THREAD

**Issue by xborn** [collectiveidea/audited#238]
I added gem in Gemfile `gem 'audited', '~> 4.0'`. After running `rails generate audited:install`
**I've got Could not find generator 'audited:install'**. What's wrong?

**Comment by danielmorrison** [comment]
Try gem "audited-activerecord" instead.

**Comment by AlfredoRoca** [comment]
It worked for me. Thanks.

**Comment by Vasfed** [comment]
I think this should be reflected in readme

**Comment by cyberwolfru** [comment]
Worked for me too. 
Why is this like this?

**Comment by ailinykh** [comment]
@cyberwolfru cause the _master_ branch is still unstable, you should use [branch 4.2](https://github.com/collectiveidea/audited/tree/4.2-stable)

**Comment by franzejr** [comment]
Yeah. Thanks, guys! It worked for me too.

**Comment by atmos** [comment]
:heart:

**Comment by seeReadCode** [comment]
An update to the README sounds in order ... unless I missed something

**Comment by danielmorrison** [comment]
The README is correct in the [4.2-stable branch](https://github.com/collectiveidea/audited/tree/4.2-stable) and `master`'s readme correctly tells people to look there. 

Master now does away with the extra gems, so really a new major release is in order.

**Comment by seeReadCode** [comment]
:eyes: indeed.  thanks!

**Comment by paneer-tikka** [comment]
If you are using rails 5, simply add this to your Gemfile (assuming you understand the risks:) - 
`gem "audited", github: 'collectiveidea/audited'`
