### ISSUE TITLE
Forced database connection on initialization

### ISSUE THREAD

**Issue by agios** [collectiveidea/audited#239]
The call to primary_key on [auditor.rb#L88](https://github.com/collectiveidea/audited/blob/1f7724a1ab5a883f6dbe55e8c82abb7b0acffa0d/lib/audited/auditor.rb#L88) triggers a database connection when the class is initialized.

This breaks not only the Rails 4 convention, but also any environment that needs to load the application files without a database. Eg, if building a Docker image on a server where the database is not accessible, asset precompilation fails because the models that use Audited cannot be loaded.

**Comment by ulfmagnetics** [comment]
+1 This issue also breaks the `rake db:setup` task, which was breaking our CI builds. @agios's PR fixed the problem for us (thx!)

**Comment by racx** [comment]
This issue is still happening. Having trouble building a Docker triggering a DB connection. @kwent fork worked for me.

**Comment by kwent** [comment]
@danielmorrison any clues ?

**Comment by danielmorrison** [comment]
I'll take a look 'cause I thought we fixed this but obviously didn't.

**Comment by danielmorrison** [comment]
#285 merges changes from @kwent. Please check and see if this helps and we can get it merged if so.

**Comment by kwent** [comment]
That helped ! Thanks for the merge.
