### ISSUE TITLE
Schema changes issue when using object.revisions

### ISSUE THREAD

**Issue by sb25** [collectiveidea/audited#24]
Say I have the following process:
1. I have a table with fields A and B.
2. An object O is created using this "schema". 
3. I alter the table by adding a new field C.
4. I update O with a value for C.

Ok, when I have a look at O.audits.changes at the step where I give a value for C, I get: 
    'null' => 'my_value_for_C'. (value at version 1 => value at version 2 )
That looks alright.

Now, when I use:
    O.revisions.each do |revision|
      puts "Version #{revision.version}: #{revision.c}"
    end

I get something like:
    Version 1: 'my_value_for_C'
    Version 2: 'my_value_for_C'

Instead of:
    Version 1: 'null'
    Version 2: 'my_value_for_C'

Should this be an expected behaviour?

I'd like to use this way of fetching revisions because they are actually representations of my object, as opposed to using "O.audits" that give me Audit objects.

Thank you for your help!

**Comment by laserlemon** [comment]
Hi there! We’re doing some open source maintenance work and closing old PRs. If you would still like this PR to be merged in, please re-open it by 2-weeks-from-today. Thanks!
