### ISSUE TITLE
associated_audits sorting in wrong column 

### ISSUE THREAD

**Issue by dgmike** [collectiveidea/audited#245]
O was trying to get associated changes but the sort was using `version` column. This column references each associated audit, in real sort must use `created_at` column instead, so sort order will be correct.

``` ruby
Proposal.take.associated_audits
```

``` sql
--  Proposal Load (0.4ms)
SELECT  `proposals`.*
  FROM `proposals`
  LIMIT 1

--  Audited::Adapters::ActiveRecord::Audit Load (0.5ms)
SELECT  `audits`.*
  FROM `audits`
  WHERE `audits`.`associated_id` = 1
    AND `audits`.`associated_type` = 'Proposal'
  ORDER BY `audits`.`version`
```

**Comment by arif-trackmy** [comment]
I'm having the same problem. associated_audits are always sort by version instead of any other column. Any update ?

**Comment by ibrahima** [comment]
I realize this is old, but was also wondering about this. It looks like there's a default sort on versions, but you can use [reorder](https://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-reorder) to change that.

**Comment by dgmike** [comment]
I will close this one...
