### ISSUE TITLE
Removing relations not being audited

### ISSUE THREAD

**Issue by JamesChevalier** [collectiveidea/audited#246]
I'm using [Associated Audits](https://github.com/collectiveidea/audited/tree/4.2-stable#associated-audits) on a `has_many through` relation. I see `create` audits for the `through` model being added, but I do not see any audits when that relation is removed.

Here are my 3 models. A `Post` can be in multiple `Categories`.

```ruby
class Post < ActiveRecord::Base
  audited
  has_associated_audits

  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations
end
```

```ruby
class Category < ActiveRecord::Base
  audited
  has_associated_audits

  has_many :categorizations, dependent: :destroy
  has_many :posts, through: :categorizations
end
```

```ruby
class Categorization < ActiveRecord::Base
  audited
  audited associated_with: :post
  audited associated_with: :category

  belongs_to :category
  belongs_to :post
end
```

My `Post` form has a pile of checkboxes for categorization:

    <%= f.association :categories, as: :check_boxes, collection: Category.order(:name), label_method: :name, value_method: :id, label: false %>

- When I edit an existing `Post` and **check** a box for a `Category`, I **do** see a new audit entry with a `create` value in the audit's action field.
- When I edit an existing `Post` and **uncheck** a box for a `Category`, I **do not** see a new audit entry.
- I do see `destroy` audits for both the `Post` and the `Categorization` auditable_type fields when I delete a `Post`, so that aspect works nicely.

1. Can audited track those deselections? If so, how?
2. Is there anything obviously bad/wrong about my audited setup in the models above? There's no `has_many through` documentation to follow, so I guessed a bit.

Thanks!

**Comment by danielmorrison** [comment]
@jasonroelofs is this related to what you ran into?

**Comment by jasonroelofs** [comment]
I had a slightly different issue but I believe it's the same underlying problem. Specifically this Rails ticket: https://github.com/rails/rails/issues/7618, whereas `destroy` events are not called through `has_many :through` relationships.

If you add `dependent: :destroy` on each of your `has_many :through`, that should fix your problem. It's very misleading, this will not destroy the base record (`post` or `category`).

**Comment by JamesChevalier** [comment]
Yes! That did it!
I basically had to swap out my `dependent: :destroy` lines:

```ruby
class Post < ActiveRecord::Base
  audited
  has_associated_audits

  has_many :categorizations
  has_many :categories, through: :categorizations, dependent: :destroy
end
```

```ruby
class Category < ActiveRecord::Base
  audited
  has_associated_audits

  has_many :categorizations
  has_many :posts, through: :categorizations, dependent: :destroy
end
```

With this setup in place, I'm seeing both create and destroy audits.
Thanks!!

**Comment by jasonroelofs** [comment]
Awesome, glad to help!
