### ISSUE TITLE
`associated_id`, `associated_type`, `user_id` and `username` are all null

### ISSUE THREAD

**Issue by artsyca** [collectiveidea/audited#255]
Steps to reproduce.

1) Audit User model and a resource (not sure if this is the correct setup?)
```ruby
class User < ActiveRecord::Base
  audited
  ...
end
```

```ruby
class Payment < ActiveRecord::Base
  audited
  ...
end
```

2) Create a resource in a controller. (`current_user` is confirmed working)

```ruby
class PaymentController
...
    def create
      Payment.create(params)
      ...
    end
...
end
```

3) Audit has no `associated_id`, `associated_type`, `user_id` and `username`, `Payment.last.audits.user` is `nil`

Expected Behaviour

`Payment.last.audits.user` should be the `current_user`

Is this a setup issue on my part? Your help is greatly appreciated.

**Comment by artsyca** [comment]
By the way, this is using `gem "audited-activerecord", "~> 4.0"`

**Comment by artsyca** [comment]
Manually wrapping in 

```
Audited.audit_class.as_user(current_user) do
...
end
```

results in the user_id being stored though..

**Comment by artsyca** [comment]
Seems to be an issue with `ApplicationController` vs. `BaseController` not having the `current_user` method properly implemented. I expect this isn't quite an issue with this gem. Closing the issue.

**Comment by GabKlein** [comment]
I'm having the same issue. The user is not set by default but only when I'm using `as_user` manually.

```
audited (4.2.0)
audited-activerecord (4.2.0)
devise (4.0.0)
```

**Comment by GabKlein** [comment]
Since I'm using `rails-api` I had to patch the `Sweeper` class

```ruby
# initializer
module Audited
  class Sweeper < ActionController::Caching::Sweeper
    if defined?(ActionController) && defined?(ActionController::API)
      ActionController::API.class_eval do
        around_action Audited::Sweeper.instance
      end
    end
  end
end
```
