### ISSUE TITLE
Audits is empty for old data in the database

### ISSUE THREAD

**Issue by sadiksha** [collectiveidea/audited#256]
Hi,
I recently added audits to my existing model. However, for the old entries, I have empty array when I do model.audits. Is there any work around for it?

**Comment by leonelgalan** [comment]
@sadiksha, i'm not a maintainer, but I'm sure the answer is **no**. `audited` can't know what it doesn't know, so all changes previous to installing `audited` won't be available.

**Comment by kennethkalmer** [comment]
@sadiksha, @leonelgalan is absolutely right.
