### ISSUE TITLE
Flip ID and type columns for indexes in generator

### ISSUE THREAD

**Issue by dukedave** [collectiveidea/audited#262]
This is regarding [the indexes added by the generator](https://github.com/collectiveidea/audited/blob/c4a0e6d96b816177165481852f97974d326bdd2c/lib/generators/audited/templates/install.rb#L20).

Specifically:

```
    add_index :audits, [:auditable_id, :auditable_type], :name => 'auditable_index'
    add_index :audits, [:associated_id, :associated_type], :name => 'associated_index'
    add_index :audits, [:user_id, :user_type], :name => 'user_index'
```

Specifically the order of `[:auditable_id, :auditable_type]`:

---

I presume they were implemented this way around because the `auditable_id` is [the most selective field](http://stackoverflow.com/a/6170023/21115).
So for queries which specify both an ID and type (e.g. `my_foo.audits`) this makes sense.

However, this index is not usable when querying all the audits for a specific `auditable_type`, e.g:

```
Audit.where(auditable_type: 'Foo')` 
```

If the order of columns in the index definition were changed to `[:auditable_type, :auditable_id]` this index would be usable.

Further: I can't think of a query in which we'd be look up an audit solely on `auditable_id`, without caring what what its `auditable_type` is.

So my question is:
Does the (unknown, and potentially neligable) performance advantage of having the more selective column first, outweigh the advantage of being able to efficiently query all audits for a specific auditable type (and if we apply the change to the other indexes, the associated object and user types)?

**Comment by kennethkalmer** [comment]
This is very interesting, I've certainly never thought about it in this way. Are you absolutely sure the databases will behave this way? For my benefit, and other readers in the future, could you provide some `EXPLAIN` output for your data to show how the query planner behaves with the current index and the change of order?

As for the history, I'm sure it could be as simple as a Rails-ism, ordering the fields alphabetically or just ordering them like that with no real thought other than _we need an index over both columns_.

Thanks for reporting!

**Comment by dukedave** [comment]
Certainly!
Here's what it looks like with PostgreSQL.
If someone else would like to test with other DBs that'd be great :smile: 

Looking for all audits on a `Sale`:

```
explain select * from audits where auditable_type = 'Sale';
```

With the currently generated index (i.e. `[:auditable_id, :auditable_type]`), we get:

```
                             QUERY PLAN                             
--------------------------------------------------------------------
 Seq Scan on audits  (cost=0.00..692352.55 rows=2337129 width=1778)
   Filter: ((auditable_type)::text = 'Sale'::text)
(2 rows)
```

Oh look :arrow_up:  a [sequential scan](https://en.wikipedia.org/wiki/Full_table_scan), aka:

> usually the slowest method of scanning a table

Now I'll add an index with ID and type flipped around (i.e. `:auditable_type, :auditable_id]`).
I'm presumptuously calling it the 'sane' version, so we can ensure that it is being used:

```
create index auditable_index_sane on audits(auditable_type, auditable_id); 
```

Running the `explain` again, we get:

```
                                         QUERY PLAN                                          
---------------------------------------------------------------------------------------------
 Bitmap Heap Scan on audits  (cost=54113.31..575400.42 rows=2337129 width=1778)
   Recheck Cond: ((auditable_type)::text = 'Sale'::text)
   ->  Bitmap Index Scan on auditable_index_sane  (cost=0.00..53529.03 rows=2337129 width=0)
         Index Cond: ((auditable_type)::text = 'Sale'::text)
(4 rows)
```

***

Some entirely unscientific numbers.
For an audits table with 16M rows, of which 2M are `Sale`.

```
select count(*) from audits where auditable_type = 'Sale';
```

* Approx. 7 seconds without index
* Approx. 1 second with index
* Approx. 3 mins to create the index

**Comment by key88sf** [comment]
@dukedave Is right -- the existing index should have the type first to be usable in practice.

Also -- why are the index names specified directly in the migration templates, instead of letting Rails auto-generate them? `user_index` seems like it could easily collide with someone's other database indices.

**Comment by tbrisker** [comment]
This has been resolved by https://github.com/collectiveidea/audited/pull/385
