### ISSUE TITLE
Could not find generator 'audited:install'

### ISSUE THREAD

**Issue by krtschmr** [collectiveidea/audited#278]
`rails g audited:install`

  `gem "audited", "~> 4.0"
`
```

  * rails (4.2.6)
  * audited (4.2.0)
  * rails-observers (0.1.2)

```

**Comment by krtschmr** [comment]
forget it. didn't see there's a 
`gem "audited-activerecord", "~> 4.0"`

**Comment by danielmorrison** [comment]
Yep, the README is for a forthcoming new version where we won't need the separate gems.

Sorry for the confusion, but glad you figured it out!
