### ISSUE TITLE
audited-activerecord is unified to audited?

### ISSUE THREAD

**Issue by junaruga** [collectiveidea/audited#281]
Hi,
I saw that audited-activerecord.gemspec has been disappeared on master branch.
Is its function merged to audited gem package from audited-activerecord gem, supporting activerecord 5, right?

**Comment by ersatzryan** [comment]
Correct. Previously there was a version for active record as well as mongomapper. Mongomapper version has been removed and audited now only supports active record.

**Comment by dmitry** [comment]
I think it's worth to notice that somewhere in the readme.

**Comment by danielmorrison** [comment]
It is only an issue right now because the master branch has departed from the gem versions (which _is_ mentioned in the README). The next big version will deprecated the old gems and we'll make sure to have proper documentation.
