### ISSUE TITLE
difference audited and audited-activerecord

### ISSUE THREAD

**Issue by krtschmr** [collectiveidea/audited#283]
can anybody pls explain when to use audited and when audited-activerecord?

i just dont get it

**Comment by dmitry** [comment]
@krtschmr please look: https://github.com/collectiveidea/audited/issues/281

The difference I found `audited` doesn't have any namespace, everything else looks like the same as it were before.

**Comment by krtschmr** [comment]
thank you

**Comment by danielmorrison** [comment]
Audited currently supports activerrecord and mongomapper, but the master branch has removed mongomapper support. 

However, the current gem versions still have the separate gems. That will go away soon.
