### ISSUE TITLE
Version 4.2 with Rails 5

### ISSUE THREAD

**Issue by I-Am-Abacus** [collectiveidea/audited#284]
The readme for the development version of audited states:-
"Audited currently (4.x) works with Rails 5.0 and 4.2. It also may work with 4.1 and 4.0, but this is not guaranteed."

Could you please clarify if this means that version 4.2 should work with Rails 5? The readme in version 4.2 does not mention Rails 5, so I'm guessing it doesn't?

Many thanks, Martin

**Comment by danielmorrison** [comment]
We're waiting on a new version of the rails-observers gem (see #276) but if that doesn't happen soon, we'll update without waiting. 

The gem versions do currently work, you just have to point to the github version of rails-observers as listed in in the Readme

**Comment by huetsch** [comment]
What exactly is broken with the rails-observers gem? Seems like it should be functional with Rails 5:

https://github.com/rails/rails-observers/commit/ba1c906475dac53bb24c51ccdb6ad8e7d0e71270

Are you just pending a fixed release from them so that you can add a fixed-version dependency?

**Comment by danielmorrison** [comment]
Yes, need a new release. There may be things preventing that on their side, but I'm not sure.

**Comment by victorsosa** [comment]
Yes, need a new release.

**Comment by nicwillemse** [comment]
has anyone reached out to them ?

**Comment by danielmorrison** [comment]
I have heard a new release is coming, but I haven't done the work to see what exactly is holding it up.

**Comment by tarujain20** [comment]
Hello, Just curious is there are any updates.

**Comment by danielmorrison** [comment]
@tarujain20 we've updated `audited`, you just need to follow the instructions in the readme for `rails-observers` since there hasn't been a release of that.
