### ISSUE TITLE
Could not find generator 'audited:install'

### ISSUE THREAD

**Issue by andy-harper** [collectiveidea/audited#290]
Rails 5.0.0.1
audited (4.2.2)

Gemfile
```
gem 'audited', '~> 4.0'
gem 'rails-observers', github: 'rails/rails-observers'
```

```
rails generate audited:install
Could not find generator 'audited:install'. Maybe you meant 'devise:install', 'cocoon:install' or 'settings:install'
Run `rails generate --help` for more options.
```

**Comment by danielmorrison** [comment]
Point audited to the `rails5` branch for now and it should fix this.

**Comment by NateJBeck** [comment]
Based on suggestion above, I used `gem "audited", github: "collectiveidea/audited", branch: "rails5"` and the generator worked as expected.

**Comment by danielmorrison** [comment]
Perfect. We'll get a new release out soon. I wanted to wait for `rails-observers` to get released, but we don't really need to wait.

**Comment by wee007** [comment]
This doesn't seem to work for me on Rails 5.0.0.1. 

Gemfile
```
gem "audited", github: "collectiveidea/audited", branch: "rails5"
gem "rails-observers", github: 'rails/rails-observers'
```

```
bundle install
```

```
rails generate audited:install
Running via Spring preloader in process 92575
Could not find generator 'audited:install'. Maybe you meant 'pundit:install', 'devise:install' or 'rspec:install'
Run `rails generate --help` for more options.

```

**Comment by danielmorrison** [comment]
@wee007 version 4.3.0 is the most up-to-date. Use that and please open a new issue if you continue to have problems.
