### ISSUE TITLE
Issue when we upgrade to Rails 5 with latest audited

### ISSUE THREAD

**Issue by nishajgd** [collectiveidea/audited#300]
Thanks in advance for support.

I am using the active_scaffold (3.2.20) and latest audited 4.3.0 with rails 5.0.0.1 and ruby 2.3.1

`bundler/gems/active_scaffold-d9b396492fc4/lib/active_scaffold/helpers/controller_helpers.rb:5:inblock in included': undefined method helper_method' for ActionController::API:Class (NoMethodError) from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/active_scaffold-d9b396492fc4/lib/active_scaffold/helpers/controller_helpers.rb:5:inclass_eval'
from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/active_scaffold-d9b396492fc4/lib/active_scaffold/helpers/controller_helpers.rb:5:in included'`

Can you please support so that we can go live asap by fixing this issue? Thanks alot!

**Comment by danabrit** [comment]
Looks like you got this worked out with active_scaffold - https://github.com/activescaffold/active_scaffold/issues/514 . Closing this issue for now. Happy coding!
