### ISSUE TITLE
undefined method `request_uuid' when running Rspec

### ISSUE THREAD

**Issue by linda-peirce** [collectiveidea/audited#309]
Have just upgraded a Rails 3 app to Rails 4, and in the process I upgraded audited to 4.3.0. I have updated the gem and run the migration. I'm still working on setting up strong params so I do have the protected_attributes gem running. I have updated each model to:

  audited allow_mass_assignment: true
  attr_protected :audit_ids

However, all my Rspec tests that save records now fail. I get the following error for each:

NoMethodError:
         undefined method `request_uuid' for  #<Audited::Audit:0x007ffb6784bb00>

I have added attr_accessor :request_uuid as suggested per [this issue](https://github.com/collectiveidea/audited/issues/225) to the audit.rb file in the gem, but that hasn't helped either. Please help!

**Comment by danielmorrison** [comment]
You need to run the upgrade step:

```
$ rails generate audited:upgrade
$ rake db:migrate
```

**Comment by linda-peirce** [comment]
I did that. Sorry, that's what I meant when I say I upgraded the app and ran the migration.

**Comment by linda-peirce** [comment]
The request_uuid field is present in the Audit table.
