### ISSUE TITLE
undefined method `request_uuid' when running Rspec

### ISSUE THREAD

**Issue by linda-peirce** [collectiveidea/audited#310]
Have just upgraded a Rails 3 app to Rails 4, and in the process I upgraded audited to 4.3.0. I have run the following commands per the gem documentation: 

```
$ rails generate audited:upgrade
$ rake db:migrate

```

I'm still working on setting up strong params so I do have the protected_attributes gem running. I have updated each model to:

```
audited allow_mass_assignment: true
attr_protected :audit_ids
```

However, all my Rspec tests that save records now fail. I get the following error for each:

```
NoMethodError:
undefined method `request_uuid' for #Audited::Audit:0x007ffb6784bb00
```

I have added attr_accessor :request_uuid as suggested per this issue to the audit.rb file in the gem, but that hasn't helped either. Please help!

**Comment by danielmorrison** [comment]
Make sure you're doing `attr_accessible` not `attr_accessor`. I think that's the issue.

**Comment by linda-peirce** [comment]
I have tried it that way as well, but no luck.

**Comment by linda-peirce** [comment]
This is the line that is kicking off the error:
gems/audited-4.3.0/lib/audited/audit.rb:141:in `set_request_uuid'

**Comment by danielmorrison** [comment]
Is it possible you haven't run `rake db:test:preprare` after running the migration?

**Comment by linda-peirce** [comment]
Ah, yes, of course, that was the issue. Thanks!
