### ISSUE TITLE
Why we don't have Audits model in rails ?

### ISSUE THREAD

**Issue by wonderer007** [collectiveidea/audited#314]
I am using audited gem and want some changes in Audit model like I want my Audit model to act as tenant is there any way I can access Audit model ?

**Comment by danielmorrison** [comment]
Yep, depending on the gem version, you can use `Audited::Audit` or `Audited.audit_class`

If you're doing it frequently you can also do `Audit = Audited::Audit` and then simply reference it as `Audit`

**Comment by nickrivadeneira** [comment]
@danielmorrison Using `Audit = Audited::Audit` doesn't work if you access audits via the `#audits` association on the auditable. The association will return `Audited::Audit` instances, without the model changes.

I like the pattern of allowing users to define a class that inherits from or includes the base `Audit` implementation, which would then get used internally by the gem. Similar patterns can be found in [`cancancan`](https://github.com/CanCanCommunity/cancancan) (define `Ability` class and include their module) and [`devise`](https://github.com/plataformatec/devise) (for custom controller implementation, define new controllers that inherit from the base controller and override methods).

If you guys are in favor, I'd be up for writing something to that effect.

**Comment by danielmorrison** [comment]
@nickrivadeneira I'm for it!

**Comment by nickrivadeneira** [comment]
@danielmorrison Opened a PR - #319. I tested it in one of our apps and it seems to work well.
