### ISSUE TITLE
Skip audit at create and save only edits

### ISSUE THREAD

**Issue by wonderer007** [collectiveidea/audited#315]
I want to save audits of only edit not save is there any option for this ?

**Comment by programmingJOJO** [comment]
Is this helpful?
https://github.com/collectiveidea/audited#specifying-callbacks

E.g.:
> Single field, only audit Update and Destroy (not Create)
  audited only: :name, on: [:update, :destroy]

**Comment by danabrit** [comment]
@wonderer007 Looks like @programmingJOJO pointed you to the exact right documentation to limit the actions that are audited. Good luck to you!
