### ISSUE TITLE
Return nil on invalid revision number

### ISSUE THREAD

**Issue by clothesline0909** [collectiveidea/audited#321]
When I try to access a revision that doesn't exist e.g. model.revision(n), where n is larger than model.revisions.length, I expect the method to return nil or an exception; however it just returns the last revision.

**Comment by danielmorrison** [comment]
Something we never thought of. I'd be open to a PR with this.

**Comment by JonathanWThom** [comment]
Hello, it doesn't look like a PR has been made for this yet. I'm going to see if I can come up with a fix, if no one else has yet.

**Comment by tbrisker** [comment]
This has been resolved in https://github.com/collectiveidea/audited/commit/7c4fb94fe6df1a8ab655a689e2062ee496c9241e
