### ISSUE TITLE
audited does not detect clob data-type (oracle)

### ISSUE THREAD

**Issue by NileshPanchal** [collectiveidea/audited#334]
The dump and load methods of class YAMLIfTextColumnType in audit.rb , use sql_type to determine if the serialisation should happen as a JSON or not .
Oracle returns 'clob' for the 'text' data-type , which fails the check..

Is checking for different sql_types the correct way to fix this ? I can send a PR if it is..

      def dump(obj)
        if Audited.audit_class.columns_hash["audited_changes"].sql_type == "text"
          ActiveRecord::Coders::YAMLColumn.new(Object).dump(obj)
        else
          obj
        end
      end

**Comment by domcleal** [comment]
Yes, or perhaps using `.type` would work more reliably?

**Comment by NileshPanchal** [comment]
`.type` returns :text. it works.
will send a PR for this.

**Comment by NileshPanchal** [comment]
submitted PR for the change.
https://github.com/collectiveidea/audited/pull/335
