### ISSUE TITLE
audit.user no longer stored on 4.4.1

### ISSUE THREAD

**Issue by morgoth** [collectiveidea/audited#336]
After updating audited from 4.3.0 to 4.4.1 `user` is no longer stored in audited record which is supposed to be `current_user` from controller

**Comment by domcleal** [comment]
Can you provide a reproducer? I'm using 4.4.1 and the user does appear to be set correctly from my controller's `current_user` method.

Please check if the method is called and consider adding debug to `Audited::Sweeper` to determine if the callback is being run and the thread variable set. (This was refactored in 87d402a between these releases.)

**Comment by morgoth** [comment]
After quick debugging, I can see that somehow order of callbacks changed.

In our case `current_user` returns nil, because it's set in `before_action` callback.

Having something like:
```ruby
class ApplicationController
  before_action -> { set current user here }
end
```
Now around callback from audited gem starts before that one, thus current user is not set yet

**Comment by domcleal** [comment]
Yeah, relying on the callback to set the value before audited's callback would be tricky. A few thoughts:

1. Use `prepend_before_action` to try and register your callback earlier than audited's.
1. Refactoring - move/share the before_filter's logic with `current_user` so it always returns a value
1. Change `before_filter` to an `around_filter` and wrap the request with `Audited::Audit.as_user`.

Sorry about the break, but I think you might need to change the app in some way here - unless you have a suggestion for how the 'sweeper' could call it more reliably.

**Comment by hashwin** [comment]
This is terrible, this has left a bunch of audits without the particular user that made the change. Downgraded back to 4.3.

**Comment by hashwin** [comment]
I'm not even setting the current_user in a before filter. I'm using devise, which should set it.

**Comment by domcleal** [comment]
> I'm not even setting the current_user in a before filter. I'm using devise, which should set it.

I'm not fully familiar with devise, but I'm unable to reproduce this using a test application. Calling `current_user` in a controller after logging in always seems to return a result (https://github.com/plataformatec/devise/blob/v4.2.1/lib/devise/controllers/helpers.rb#L123-L125 suggests it would too).

Like above, check that the `current_user` method is always returning a result.

**Comment by lucianosousa** [comment]
it's related to #343

**Comment by domcleal** [comment]
PR #344 is open, which should fix this issue. Thanks for all of the feedback, and the reproducer from @lucianosousa in #343! (Which now works with that branch.)

**Comment by lucianosousa** [comment]
@domcleal thanks. I'll test this soon as possible.

**Comment by amedrz** [comment]
@domcleal @lucianosousa is this working for you guys? I just hit the same issue while on v4.1 and upgraded to v4.5 but kept happening. Had to downgrade to v4.3 and now it works.

```
actionpack (5.0.2) lib/action_controller/metal/request_forgery_protection.rb:195:in `handle_unverified_request'
actionpack (5.0.2) lib/action_controller/metal/request_forgery_protection.rb:223:in `handle_unverified_request'
devise (4.2.1) lib/devise/controllers/helpers.rb:253:in `handle_unverified_request'
actionpack (5.0.2) lib/action_controller/metal/request_forgery_protection.rb:218:in `verify_authenticity_token'
activesupport (5.0.2) lib/active_support/callbacks.rb:382:in `block in make_lambda'
activesupport (5.0.2) lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
actionpack (5.0.2) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
activesupport (5.0.2) lib/active_support/callbacks.rb:170:in `block in halting'
activesupport (5.0.2) lib/active_support/callbacks.rb:454:in `block in call'
activesupport (5.0.2) lib/active_support/callbacks.rb:454:in `each'
activesupport (5.0.2) lib/active_support/callbacks.rb:454:in `call'
activesupport (5.0.2) lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
activesupport (5.0.2) lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
audited (4.5.0) lib/audited/sweeper.rb:14:in `around'
activesupport (5.0.2) lib/active_support/callbacks.rb:405:in `public_send'
activesupport (5.0.2) lib/active_support/callbacks.rb:405:in `block in make_lambda'
activesupport (5.0.2) lib/active_support/callbacks.rb:285:in `block in halting'
activesupport (5.0.2) lib/active_support/callbacks.rb:447:in `block in around'
activesupport (5.0.2) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.2) lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
activesupport (5.0.2) lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
audited (4.5.0) lib/audited/sweeper.rb:14:in `around'
```

**Comment by lucianosousa** [comment]
@amedrz last time I was trying it works.
you can test in this app: https://github.com/lucianosousa/rails5_test to reproduce the errors if you want
