### ISSUE TITLE
document in readme that authentication has to be performed before controller is hit

### ISSUE THREAD

**Issue by grosser** [collectiveidea/audited#340]
spent a while figuring out why my user was not logged ... turns out the around_action runs after my `authenticate` before_action ... so needed to do `  prepend_before_action :authenticate!` would be nice to state that in the docs

**Comment by domcleal** [comment]
Thanks for the report, but after a number of other users hitting the same issue in #336, I'm going to fix this rather than document the workaround. Cheers.
