### ISSUE TITLE
Deprecation Warning in Rails 5.2

### ISSUE THREAD

**Issue by rafaelss95** [collectiveidea/audited#350]
Hi,

In the following statement:

`audits = Version.auditable_finder(xx, 'some_string')`

The prompt shows this warning:

> DEPRECATION WARNING: Passing a class as a value in an Active Record query is deprecated and will be removed. Pass a string instead. (called from...)

**Comment by domcleal** [comment]
What is `xx` in your query? If it's a class, call `xx.name` and pass it in. Both instances of this scope call inside audited itself look to be correctly passing IDs/strings.

**Comment by rafaelss95** [comment]
"xx" refers to `auditable_id` (numbrer) and the other parameter refers to the `auditable_type` (string). Ex: auditable.finder(1, 'MyType').

**Comment by domcleal** [comment]
The scope is extremely simple, so I can't see how that warning could be generated:

    scope :auditable_finder, ->(auditable_id, auditable_type){ where(auditable_id: auditable_id, auditable_type: auditable_type)}

Either the value of `auditable_id` or `auditable_type` you're passing in must be a class in order to trigger that deprecation warning. Can you re-check please?

Also, is `Version` an alias to `Audited::Audit` or do you have some extensions to the class? Is it a subclass, are there any overrides such as a default scope that might be causing the warning?

**Comment by rafaelss95** [comment]
So, instead a string it must be a *class*?

Ex: Imagine that I want to search for model `Address` and id 1, so instead of:

`auditable_finder(1, 'Address')`

I should go for:

`auditable_finder(1, Address)`

Passing the model itself, instead of string?

`Version` is a custom audit model. I didn't override nothing yet..

**Comment by domcleal** [comment]
> So, instead a string it must be a class?

No, sorry. It should be a string. I meant the deprecation warning suggests one of them _is_ a class. It should be a string.

> Version is a custom audit model. I didn't override nothing yet..

Can you reproduce the warning with `Audited::Audit.auditable_finder`?

If you can post a reproducer app, it would be appreciated as I'm unable to see how such a simple scope could cause this warning with the given inputs. Thanks!

**Comment by rafaelss95** [comment]
@domcleal Thanks, man. You were totally right, the error was on my side. I though I was passing a `string` but definitely not. Sorry for this unnecessary issue.
