### ISSUE TITLE
update_all

### ISSUE THREAD

**Issue by davidsavoya** [collectiveidea/audited#352]
Not sure if this is a bug or designed this way, but when I update an audited field on a active record relation using update_all, I am not getting audits created. Let me know if you need more info. I am using 4.2.

**Comment by domcleal** [comment]
I think this is reasonably documented in ActiveRecord: ["It does not instantiate the involved models and it does not trigger Active Record callbacks"](https://apidock.com/rails/ActiveRecord/Base/update_all/class). The audited gem is an AR extension so it does need the models and callbacks to work - performing an update directly against the database or with SQL-only methods like update_all won't create audits.

To get auditing support, you'll need to instantiate the models, i.e. `relation.find_each { |model| m.update_attributes(..) }`

**Comment by davidsavoya** [comment]
Ok that makes sense. Thanks for feedback.
