### ISSUE TITLE
"version" accessor in audited models clobbers "version" column (if present)

### ISSUE THREAD

**Issue by yzhanginwa** [collectiveidea/audited#37]
when I need to audit a table with a column name "version". 

I figured out a workaround for it. But it would be nice to remove the use of "attr_accessor :version" or rename the ":version" to to a not-so-common column name.

**Comment by joonty** [comment]
I've just run into exactly the same issue. Took me a while to work out why my application stopped working after adding auditing to one of my models, but this was it - the `version` method that audited added returns `nil`, which breaks things.

:+1: for not defining extra methods on the model!

**Comment by bdiz** [comment]
@kennethkalmer, would you like us to take a stab at this? We would really like the ability to change the name of the :version attr_accessor on our models to get rid of our monkey patches. Let us know if you'd have time to accept our PR before we spend time on it. Thanks.

**Comment by laserlemon** [comment]
Hi there! We’re doing some open source maintenance work and closing old issues. If you would still like this PR to be merged in, please re-open it by 2-weeks-from-today. Thanks!
