### ISSUE TITLE
Deprecation warning for changed_attributes with rails 5.1

### ISSUE THREAD

**Issue by aandis** [collectiveidea/audited#371]
Calling `update_attributes` in my model when using audited shows the following deprecation warning

> #### DEPRECATION WARNING: The behavior of `changed_attributes` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_changes.transform_values(&:first)` instead.

I believe this is coming from https://github.com/collectiveidea/audited/blob/f8433d47cf998cd7acb12b2337bd5cddca643947/lib/audited/auditor.rb#L181

**Comment by farisj** [comment]
+1
