### ISSUE TITLE
Select objects without audit

### ISSUE THREAD

**Issue by Kani999** [collectiveidea/audited#383]
Hello,
Is there any way to select all objects of certain model without audit record?

I have code like this:
```ruby
 @users_without_audit = []
    User.all.each do |user|
      @users_without_audit .push(user) if user.audits.count.zero?
    end
```

But i would like to use something like:
```ruby
 @users_without_audit = User.joins(:audit).where("count(audit.id" = 0)
```

**Comment by hernanat** [comment]
what about

```rb
User.joins('LEFT JOIN audits ON users.id = audits.auditable_id').where("audits.auditable_type = 'User'").group('users.id').having('COUNT(*) = 0')
```

**Comment by Kani999** [comment]
Yes, that make sense.
But I thought there is some "built in" syntax.
Thanks

**Comment by hernanat** [comment]
> Yes, that make sense.
But I thought there is some "built in" syntax.
Thanks

Unfortunately not :(
