### ISSUE TITLE
Best way to disable auditing in test environment?

### ISSUE THREAD

**Issue by metalelf0** [collectiveidea/audited#410]
Hi, I'm currently working on a medium-sized Rails 4 project where Audited is being used extensively. The test suite relies pretty heavily on capybara features, so the performance overhead audited is adding to our test suite is really noticeable and I'm looking for a way to get rid of it.

I've tried different approaches to disable Audited only in test environment; however the only one that is working is putting

```
  audited unless Rails.env.test?
```

in every audited model. This has downsides - first of all it's really verbose; secondly, being this evaluated just once (at class evaluation time), it doesn't allow turning audited back on if I want to test audits in some specific tests.

I've also tried putting this in my `before(:suite)` method:

```
    Audited.audit_class.audited_class_names.map(&:constantize).each do |klass|
      klass.auditing_enabled = false
    end
```
and turning audit back on in individual specs like:

```
  around :each do |example|
    audit_enabled = User.auditing_enabled
    User.auditing_enabled = true
    example.run
    User.auditing_enabled = audit_enabled
  end
```

but it seems it's much slower than the solution above (25% slower on the overall suite running time).

[EDIT]: the code above it's slower cause `Audited.audit_class.audited_class_names == []` in the `before(:suite)`, as obviously the environment hasn't still been loaded, therefor making the lines above completely useless. It works by putting it in a `before(:all)` block, but I don't like having to repeat that code for every example group in my suite.

What's the suggested solution for this problem? Thanks.

**Comment by tbrisker** [comment]
Audits are enabled or disabled at a class level, currently there is no way to enable or disable them completely. It is a very valid feature request though, if someone opens a PR that adds that allows this (shouldn't be too hard) we could include it. 
For no, I am not familiar with all the rspec internals, but I guess it would be best if you can run the disabling block after the models have been loaded and before the suite actually starts running (perhaps there is a different config option, or maybe do it outside the rspec.config scope?).

**Comment by akostadinov** [comment]
Actually disabling on class level is only per thread. So running some code in a thread runs with auditing enabled. That's unexpected.
