### ISSUE TITLE
cannot pass audit_comment option for relation#destroy_all

### ISSUE THREAD

**Issue by zoonoo** [collectiveidea/audited#421]
```
calendar.holidays.where(dates: dates_param).destroy_all(audit_comment: "this is comment.")
```

This causes error : 

```
ArgumentError - wrong number of arguments (given 1, expected 0)
```

Perhaps we should override the destroy_all method from activerecord?

activerecord/lib/active_record/relation.rb

**Comment by charlesemarsh** [comment]
I too need this, I'm trying to add a comment for the reason it was destroyed.

**Comment by tbrisker** [comment]
This doesn't work for regular `destroy` either, you always need to set the comment first. I suggest using something like:

```ruby
calendar.holidays.where(dates: dates_param).find_each do |el| 
  el.audit_comment =  "this is comment."
  el.destroy
end
```
