### ISSUE TITLE
Audited does not correctly deserialize attributes of JSON type, specifically when the value is an array

### ISSUE THREAD

**Issue by cfeckardt** [collectiveidea/audited#446]
Context:

When trying to store an array (json object) in an attribute, it returns only the last value of that array when it is audited.

Consider:
```
model Foo
  # has an attribute of type :json called my_attr
end
Foo.create(my_attr: ['hello', 'world'])

Foo.first.revision_at(0.seconds.ago).my_attr # returns 'world', expected ['hello', 'world']
```

The culprit appears to be
```
    # Returns a hash of the changed attributes with the new values
    def new_attributes
      (audited_changes || {}).inject({}.with_indifferent_access) do |attrs, (attr, values)|
        attrs[attr] = values.is_a?(Array) ? values.last : values
        attrs
      end
    end
```

In this case values is an array but we don't want to last value.

*PROPOSED SOLUTION*
Don't test for `is_a?(Array)`, but use a `class AuditArray < Array` internally instead, so that we are able to use arrays.

Thoughts?

Happy to fix this if the approach is viable to the author.

**Comment by cfeckardt** [comment]
I'm not sure I follow exactly what you mean. But I think that would still not work if you create it with a json array attribute, because it'll still be read as a historical list of values, rather than just an array.

I think that the correct solution is to *always* wrap your values in an array. Even for create or destroy. Then you can just remove that check. What do you think?

**Comment by tbrisker** [comment]
Wrapping all values in an array would only work for new audits, old audits will remain in the same state. The check here, for `values.is_a?(Array)` is incorrect - it should be `action == 'update'` instead.

**Comment by cfeckardt** [comment]
Ah yes that makes sense, you are completely right. Ignore the PR for now. I will sort it properly tomorrow.

**Comment by cfeckardt** [comment]
PR updated, ready for review @tbrisker
