### ISSUE TITLE
Conflict with Version model (Module::DelegationError)

### ISSUE THREAD

**Issue by maurymmarques** [collectiveidea/audited#461]
I have a model called "Subscription" associated (belongs_to) with a model "Version" and I'm receving an error (http://api.rubyonrails.org/classes/Module/DelegationError.html) when using "audited" in my Subscription model.
The problem happens when I use "delegate" and try to print it in some view.

![delegation_error](https://user-images.githubusercontent.com/338086/42345565-16d2cebc-8076-11e8-8c1c-8e00b8cc6686.png)

```ruby
# Subscription Model
class Subscription < ActiveRecord::Base
	audited

	belongs_to :account
	belongs_to :product
	belongs_to :version
	belongs_to :plan

        delegate :name, :email, :corporate_id, :corporate_name, :personal_id, :account_manager_id, to: :account, prefix: true
	delegate :name, to: :product, prefix: true
  	delegate :name, to: :version, prefix: true
  	delegate :name, to: :plan, prefix: true
end
```

```ruby
# Subscription View
<%= @subscription.version_name %>
```

One solution would be to do this, but I do not think it's the most appropriate way, plus I have to change many places in the system.

```ruby
# Subscription Model
class Subscription < ActiveRecord::Base
	audited

	belongs_to :account
	belongs_to :product
	belongs_to :version_model, foreign_key: :version_id, class_name: 'Version'
	belongs_to :plan

	delegate :name, :email, :corporate_id, :corporate_name, :personal_id, :account_manager_id, to: :account, prefix: true
        delegate :name, to: :product, prefix: true
	delegate :name, to: :version_model, prefix: true
	delegate :name, to: :plan, prefix: true
end	
```

```ruby
# Subscription View
<%= @subscription.version_model_name %>
```
I think it's some conflict with Audited gem. 
I appreciate any help.
Thank you.

**Comment by tbrisker** [comment]
This should be fixed by #443 once it is merged.

**Comment by maurymmarques** [comment]
It's good to know that someone is working on the solution to this problem. I'm waiting for the update to be available.
Thank you very much.

**Comment by maurymmarques** [comment]
Is there any forecast to release these changes in a new version?
I only need this to be able to install Audited in my application
Thank you.

**Comment by tbrisker** [comment]
I hope to get version 4.8.0 with this and a few other fixes out this week.

**Comment by maurymmarques** [comment]
I updated the gem to version 4.8.0 and this problem has been fixed.
It's all right and working on my application now.
Thank you very much.
