### ISSUE TITLE
Audited.audit_class.as_user not working properly for User class

### ISSUE THREAD

**Issue by CassianoSF** [collectiveidea/audited#467]
When I destroy a User, the destroyed user is audited, not the current one:

```
      Audited.audit_class.as_user(_ctx[:current_user]) do
        record = User.find_by(id: args[:id])
        return GraphQL.ExecutionError.new("VALIDATION ERROR", options: record.errors) unless record.destroy
        record
      end
    end
```

_ctx[:current_user] has User with id 1
args[:id] has 9

The Audit:

 #<Audits:0x00007f0ef133e710
 id: 80,
 auditable_id: nil,
 auditable_type: nil,
 associated_id: nil,
 associated_type: nil,
 user_id: 9,
 user_type: nil,
 username: nil,
 action: "destroy",
 audited_changes:
  {"name"=>"TestUser",
   "email"=>"test@test.com",
   "provider"=>"email",
   "uid"=>"test@test.com",
   "encrypted_password"=>
    "$2a$11$xMwYxCXwJGO6ASjbkywRpOst7oQDVBYzmZlAG7GylLuEJD9id//KO",
   "reset_password_token"=>nil,
   "reset_password_sent_at"=>nil,
   "allow_password_change"=>false,
   "remember_created_at"=>nil,
   "sign_in_count"=>0,
   "current_sign_in_at"=>nil,
   "last_sign_in_at"=>nil,
   "current_sign_in_ip"=>nil,
   "last_sign_in_ip"=>nil,
   "confirmation_token"=>nil,
   "confirmed_at"=>nil,
   "confirmation_sent_at"=>nil,
   "unconfirmed_email"=>nil,
   "nickname"=>nil,
   "image"=>nil,
   "tokens"=>{},
},
 version: 0,
 comment: nil,
 remote_address: nil,
 request_uuid: nil,
 created_at: Fri, 31 Aug 2018 11:13:46 UTC +00:00>

user_id: 9 ?  Should be 1 right?

**Comment by tbrisker** [comment]
No, `user_id`, `user_type` and `username`  fields all refer to the user performing the action.
What is wrong here is that `auditable_type` should be `User` and `auditable_id` should be `9` but they aren't - which version of rails and audited are you using?

**Comment by CassianoSF** [comment]
Sorry, my mistake. I had added a model to the audits and created a relationship between the user model

```
class Audits < ApplicationRecord
    belongs_to :usuario, class_name: "Usuario", foreign_key: :user_id
    serialize :audited_changes
end

```


```
class User < ApplicationRecord
  ...
  audited
  has_many :audits, class_name: "Audited::Audit", foreign_key: :user_id
  ...
end
```


The fix was delete the Audits model and change the relation:
`  has_many :audits, class_name: "Audited::Audit", foreign_key: :user_id
`
