### ISSUE TITLE
JRuby 1.6.0.RC1 Rails 3.0.3 Glassfish Deployment

### ISSUE THREAD

**Issue by kilaru** [collectiveidea/audited#47]
Hey Kenneth sorry to bother you again with Jruby and stuff. 

I am able to deploy by auditing my model using acts_as_audited 2.0.0.rc5
gem on Webrick successfully.

But when I do a war and try to deploy the war file on glassfish, I am
stuck with following errors. I didnt find much about this on google and
even tried all the things I found there

The occured error is like this. Can anyone please help me out

[#|2011-02-09T14:08:02.558-0600|SEVERE|glassfish3.0.1|javax.enterprise.system.container.web.com.sun.enterprise.web|_ThreadID=32;_ThreadName=http-thread-pool-8080-(1);|WebModule[/gavel]Application
Error
org.jruby.rack.RackInitializationException: undefined method
`cache_sweeper' for ActionController::Base:Class
  from
/home/dev2/.rvm/gems/jruby-1.6.0.RC1@global/bundler/gems/acts_as_audited-ccc7043d113f/lib/acts_as_audited.rb:44:in
`class_eval'
  from
/home/dev2/.rvm/gems/jruby-1.6.0.RC1@global/bundler/gems/acts_as_audited-ccc7043d113f/lib/acts_as_audited.rb:44
  from
/home/dev2/.rvm/gems/jruby-1.6.0.RC1@global/bundler/gems/acts_as_audited-ccc7043d113f/lib/acts_as_audited.rb:68:in
`require'
  from
/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler/runtime.rb:68:in
`require'
  from
/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler/runtime.rb:66:in
`each'
  from
/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler/runtime.rb:66:in
`require'
  from
/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler/runtime.rb:55:in
`each'
  from
/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler/runtime.rb:55:in
`require'
   ... 20 levels...
  from classpath:/vendor/rack-1.2.1/rack/builder.rb:46:in `initialize'
  from <web.xml>:1:in`new'
  from <web.xml>:1

  at
org.jruby.rack.DefaultRackApplicationFactory$4.init(DefaultRackApplicationFactory.java:198)
  at
org.jruby.rack.DefaultRackApplicationFactory.getApplication(DefaultRackApplicationFactory.java:61)
  at
org.jruby.rack.PoolingRackApplicationFactory.getApplication(PoolingRackApplicationFactory.java:94)
  at
org.jruby.rack.DefaultRackDispatcher.process(DefaultRackDispatcher.java:28)
  at org.jruby.rack.RackFilter.doFilter(RackFilter.java:63)
  at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
  at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:215)
  at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:277)
  at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:188)
  at
org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:641)
  at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
  at
com.sun.enterprise.web.PESessionLockingStandardPipeline.invoke(PESessionLockingStandardPipeline.java:85)
  at
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:185)
  at
org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:325)
  at
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:226)
  at
com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:239)
  at
com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:791)
  at
com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:693)
  at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:954)
  at
com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:170)
  at
com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:135)
  at
com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:102)
  at
com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:88)
  at
com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:76)
  at
com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:53)
  at
com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:57)
  at com.sun.grizzly.ContextTask.run(ContextTask.java:69)
  at
com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:330)
  at
com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:309)
  at java.lang.Thread.run(Thread.java:662)
Caused by: org.jruby.exceptions.RaiseException: undefined method
`cache_sweeper' for ActionController::Base:Class
  at
Kernel.cache_sweeper(/home/dev2/.rvm/gems/jruby-1.6.0.RC1@global/bundler/gems/acts_as_audited-ccc7043d113f/lib/acts_as_audited.rb:45)
  at
(unknown).(unknown)(/home/dev2/.rvm/gems/jruby-1.6.0.RC1@global/bundler/gems/acts_as_audited-ccc7043d113f/lib/acts_as_audited.rb:44)
  at
Module.class_eval(/home/dev2/.rvm/gems/jruby-1.6.0.RC1@global/bundler/gems/acts_as_audited-ccc7043d113f/lib/acts_as_audited.rb:44)
  at
Module.class_eval(/home/dev2/.rvm/gems/jruby-1.6.0.RC1@global/bundler/gems/acts_as_audited-ccc7043d113f/lib/acts_as_audited.rb:44)
  at
(unknown).(unknown)(/home/dev2/.rvm/gems/jruby-1.6.0.RC1@global/bundler/gems/acts_as_audited-ccc7043d113f/lib/acts_as_audited.rb:68)
  at
# Class:01x1d362c1.require(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler/runtime.rb:68)

  at
Bundler::Runtime.require(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler/runtime.rb:66)
  at
Array.each(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler/runtime.rb:66)
  at
Bundler::Runtime.require(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler/runtime.rb:55)
  at
Array.each(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler/runtime.rb:55)
  at
Bundler::Runtime.require(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler.rb:120)
  at
# Class:01x1fc79cc.require(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/config/application.rb:7)

  at
(unknown).(unknown)(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/config/application.rb:239)
  at
Kernel.require(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239)
  at
ActiveSupport::Dependencies::Loadable.require(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225)
  at
ActiveSupport::Dependencies::Loadable.load_dependency(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596)
  at
ActiveSupport::Dependencies.new_constants_in(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225)
  at
ActiveSupport::Dependencies::Loadable.load_dependency(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239)
  at
ActiveSupport::Dependencies::Loadable.require(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/config/environment.rb:2)
  at
(unknown).(unknown)(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/config/environment.rb:239)
  at
Kernel.require(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239)
  at
ActiveSupport::Dependencies::Loadable.require(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225)
  at
ActiveSupport::Dependencies::Loadable.load_dependency(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596)
  at
ActiveSupport::Dependencies.new_constants_in(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225)
  at
ActiveSupport::Dependencies::Loadable.load_dependency(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/activesupport-3.0.3/lib/active_support/depende[#|2011-02-09T14:08:02.558-0600|SEVERE|glassfish3.0.1|javax.enterprise.system.container.web.com.sun.enterprise.web|_ThreadID=32;_ThreadName=Thread-1;|WebModule[/gavel]Application
Error
org.jruby.rack.RackInitializationException: undefined method
`cache_sweeper' for ActionController::Base:Class
  from
/home/dev2/.rvm/gems/jruby-1.6.0.RC1@global/bundler/gems/acts_as_audited-ccc7043d113f/lib/acts_as_audited.rb:44:in
`class_eval'
  from
/home/dev2/.rvm/gems/jruby-1.6.0.RC1@global/bundler/gems/acts_as_audited-ccc7043d113f/lib/acts_as_audited.rb:44
  from
/home/dev2/.rvm/gems/jruby-1.6.0.RC1@global/bundler/gems/acts_as_audited-ccc7043d113f/lib/acts_as_audited.rb:68:in
`require'
  from
/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler/runtime.rb:68:in
`require'
  from
/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler/runtime.rb:66:in
`each'
  from
/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler/runtime.rb:66:in
`require'
  from
/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler/runtime.rb:55:in
`each'
  from
/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler/runtime.rb:55:in
`require'
   ... 20 levels...
  from classpath:/vendor/rack-1.2.1/rack/builder.rb:46:in `initialize'
  from <web.xml>:1:in`new'
  from <web.xml>:1

  at
org.jruby.rack.DefaultRackApplicationFactory$4.init(DefaultRackApplicationFactory.java:198)
  at
org.jruby.rack.DefaultRackApplicationFactory.getApplication(DefaultRackApplicationFactory.java:61)
  at
org.jruby.rack.PoolingRackApplicationFactory.getApplication(PoolingRackApplicationFactory.java:94)
  at
org.jruby.rack.DefaultRackDispatcher.process(DefaultRackDispatcher.java:28)
  at org.jruby.rack.RackFilter.doFilter(RackFilter.java:63)
  at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
  at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:215)
  at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:277)
  at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:188)
  at
org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:641)
  at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
  at
com.sun.enterprise.web.PESessionLockingStandardPipeline.invoke(PESessionLockingStandardPipeline.java:85)
  at
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:185)
  at
org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:325)
  at
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:226)
  at
com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:239)
  at
com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:791)
  at
com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:693)
  at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:954)
  at
com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:170)
  at
com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:135)
  at
com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:102)
  at
com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:88)
  at
com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:76)
  at
com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:53)
  at
com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:57)
  at com.sun.grizzly.ContextTask.run(ContextTask.java:69)
  at
com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:330)
  at
com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:309)
  at java.lang.Thread.run(Thread.java:662)
Caused by: org.jruby.exceptions.RaiseException: undefined method
`cache_sweeper' for ActionController::Base:Class
  at
Kernel.cache_sweeper(/home/dev2/.rvm/gems/jruby-1.6.0.RC1@global/bundler/gems/acts_as_audited-ccc7043d113f/lib/acts_as_audited.rb:45)
  at
(unknown).(unknown)(/home/dev2/.rvm/gems/jruby-1.6.0.RC1@global/bundler/gems/acts_as_audited-ccc7043d113f/lib/acts_as_audited.rb:44)
  at
Module.class_eval(/home/dev2/.rvm/gems/jruby-1.6.0.RC1@global/bundler/gems/acts_as_audited-ccc7043d113f/lib/acts_as_audited.rb:44)
  at
Module.class_eval(/home/dev2/.rvm/gems/jruby-1.6.0.RC1@global/bundler/gems/acts_as_audited-ccc7043d113f/lib/acts_as_audited.rb:44)
  at
(unknown).(unknown)(/home/dev2/.rvm/gems/jruby-1.6.0.RC1@global/bundler/gems/acts_as_audited-ccc7043d113f/lib/acts_as_audited.rb:68)
  at
# Class:01x1d362c1.require(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler/runtime.rb:68)

  at
Bundler::Runtime.require(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler/runtime.rb:66)
  at
Array.each(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler/runtime.rb:66)
  at
Bundler::Runtime.require(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler/runtime.rb:55)
  at
Array.each(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler/runtime.rb:55)
  at
Bundler::Runtime.require(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/bundler-1.0.10/lib/bundler.rb:120)
  at
# Class:01x1fc79cc.require(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/config/application.rb:7)

  at
(unknown).(unknown)(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/config/application.rb:239)
  at
Kernel.require(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239)
  at
ActiveSupport::Dependencies::Loadable.require(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225)
  at
ActiveSupport::Dependencies::Loadable.load_dependency(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596)
  at
ActiveSupport::Dependencies.new_constants_in(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225)
  at
ActiveSupport::Dependencies::Loadable.load_dependency(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239)
  at
ActiveSupport::Dependencies::Loadable.require(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/config/environment.rb:2)
  at
(unknown).(unknown)(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/config/environment.rb:239)
  at
Kernel.require(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239)
  at
ActiveSupport::Dependencies::Loadable.require(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225)
  at
ActiveSupport::Dependencies::Loadable.load_dependency(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:596)
  at
ActiveSupport::Dependencies.new_constants_in(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:225)
  at
ActiveSupport::Dependencies::Loadable.load_dependency(/home/dev2/glassfishv3/glassfish/domains/domain1/applications/gavel/WEB-INF/gems/gems/activesupport-3.0.3/lib/active_support/dependencies.rb:239)
  at
ActiveSupport::Dependencies::Loadable.require(classpath:/jruby/rack/rails.rb:169)
  at
JRuby::Rack::RailsBooter::Rails3Environment.load_environment(classpath:/jruby/rack/rails.rb:173)
  at
JRuby::Rack::RailsBooter::Rails3Environment.to_app(classpath:/jruby/rack/rails.rb:194)
  at #Class:01x11a2567.new(<web.xml>:1)
  at
(unknown).(unknown)(classpath:/vendor/rack-1.2.1/rack/builder.rb:46)
  at
Kernel.instance_eval(classpath:/vendor/rack-1.2.1/rack/builder.rb:46)
  at
Kernel.instance_eval(classpath:/vendor/rack-1.2.1/rack/builder.rb:46)
  at Rack::Builder.initialize(<web.xml>:1)
  at (unknown).new(<web.xml>:1)
  at (unknown).(unknown)(:1)
|#]

ncies.rb:239)
  at
ActiveSupport::Dependencies::Loadable.require(classpath:/jruby/rack/rails.rb:169)
  at
JRuby::Rack::RailsBooter::Rails3Environment.load_environment(classpath:/jruby/rack/rails.rb:173)
  at
JRuby::Rack::RailsBooter::Rails3Environment.to_app(classpath:/jruby/rack/rails.rb:194)
  at #Class:01x11a2567.new(<web.xml>:1)
  at
(unknown).(unknown)(classpath:/vendor/rack-1.2.1/rack/builder.rb:46)
  at
Kernel.instance_eval(classpath:/vendor/rack-1.2.1/rack/builder.rb:46)
  at
Kernel.instance_eval(classpath:/vendor/rack-1.2.1/rack/builder.rb:46)
  at Rack::Builder.initialize(<web.xml>:1)
  at (unknown).new(<web.xml>:1)
  at (unknown).(unknown)(:1)
|#]

**Comment by laserlemon** [comment]
Hi there! We’re doing some open source maintenance work and closing old issues. If this issue is still a concern, please re-open it within two weeks. Thanks!
