### ISSUE TITLE
Custom names for actions

### ISSUE THREAD

**Issue by cderche** [collectiveidea/audited#473]
Hello,

Is there a way of custom naming an `action` in Audited? i.e. instead of `update` I want it to be `approved` when a certain condition is fulfilled.

Thank you in advance.

**Comment by tbrisker** [comment]
You could extend the Audited::Auditor class in your application to introduce extra logic, such as calling the `write_audit` function when a certain action occurs with custom actions.

**Comment by tbrisker** [comment]
@cderche something like that, you might need to play around with it a bit to get it quite right with your specific business logic, but that's the general idea.

**Comment by cderche** [comment]
Thank you. Upon review, I moved ActionAudit to `app/models/audited/auditor/action_auditor.rb` and call `include Audited::Auditor::ActionAuditor` in User.rb

Closing.
