### ISSUE TITLE
`if:` and `unless:` not working

### ISSUE THREAD

**Issue by arcreative** [collectiveidea/audited#487]
There seems to be nothing I can do to get this gem execute my `audit?` method:

```ruby
class ApplicationRecord < ActiveRecord::Base
  audited if: :audit?
  ...
  private

  def audit?
    # This never executes
    true
  end
end
```

The reason I'm doing this is because I want to use a blacklist method instead of a whitelist method--I currently have a single model I don't want audited, and I'd like to do the following:

```ruby
class MyModelThatUpdatesButIDontCare < BroadcastRecord
  ...
  private
  
  def audit?
    false
  end
end
```

Am I missing something?  Could it be that the latter class inherits from a subclass of `ApplicationRecord`?  Or something else?

**Comment by deepak-sweeten** [comment]
Try to add this in application record class.

`    self.abstract_class = true`

I replicated your issue, it is working fine for me only this line is causing an issue if I delete this.

**Comment by arcreative** [comment]
@deepak-sweeten No dice :-(  I already had `abstract_class` set, but can't get anything to call it.  Tried killing spring and clearing cache in case bootsnap wasn't allowing the change, but can't get anything to actually call the `audit?` method.

**Comment by arcreative** [comment]
I think I may have misunderstood how this works... I think I was assuming this was a class method, and not evaluated on a per-instance basis.  I can see that it's being called later on in the process. Sorry about that :-)
