### ISSUE TITLE
Audit.order not working as expected

### ISSUE THREAD

**Issue by bbozo** [collectiveidea/audited#49]
I had trouble writing a view for audits, the records wouldn't sort chronologically, so I tried:

<pre>ruby-1.9.2-p0 > Audit.order("ID DESC").all.each{|a| puts a.id  }
10025
10024
10023
10020
10002
10000
10021
10001
10022</pre>

Then I tried to_sql and got surprised:

<pre>ruby-1.9.2-p0 > Audit.order("ID DESC").to_sql
 => "SELECT \"AUDITS\".* FROM \"AUDITS\" ORDER BY version, ID DESC" </pre>

Is there a workaround over this issue?

Best regards,

Borna

**Comment by ziomio** [comment]
Thanks njakobsen, you are a life saver!

**Comment by danielmorrison** [comment]
I removed the default scope in #179 for this very reason. We haven't shipped a new gem version with this, but we should before too long.

**Comment by njakobsen** [comment]
:+1:
