### ISSUE TITLE
New enum handling in 4.9.0 is a breaking change

### ISSUE THREAD

**Issue by gaffney** [collectiveidea/audited#517]
The enum change (#429) is a major breaking change but is not listed under `Breaking Changes` (data in the database still contains the enum string values).

Ideally the `CHANGELOG` would list the enum change as such, and provide a migration path for users who already rely on the behavior of `4.8.0`.

Also, semi-related - The [CHANGELOG](https://github.com/collectiveidea/audited/blob/master/CHANGELOG.md) still says `4.9.0` is unreleased even though it's in [releases](https://github.com/collectiveidea/audited/releases) (or if it's trying to show nothing under UNRELEASED, that is not very clear).

cc @fatkodima 

-----

**EDIT**: Deleted some paragraph saying that reverting #429 still produced different results - that was due to a bad merge conflict resolution 🤦‍♂ Reverting the PR fixes the issue.

**Comment by travisofthenorth** [comment]
Can someone from collectiveidea chime in here? @danielmorrison 

This is preventing upgrades to Rails 6 in a number of my applications. I have a candidate PR ready to go to allow the previous behavior: https://github.com/collectiveidea/audited/pull/526

I also have another PR to fix the build, which is currently failing: https://github.com/collectiveidea/audited/pull/530

**Comment by danielmorrison** [comment]
I'll plan to take a look later this week.

**Comment by gaffney** [comment]
Bump, any update @danielmorrison ?

**Comment by kluka-CS** [comment]
Thanks a lot for this report and the quick reversion of the feature! Prevented huge confusion for anyone reading our database.
