### ISSUE TITLE
Any way to append onto the end of audit_changes?

### ISSUE THREAD

**Issue by KevinInTx** [collectiveidea/audited#54]
I know that there is a comment field in the audits table but we are using that for something else.
We need a way to have that the password was changed without showing what it was/is now.
We were thinking of just appending on to the end of the audit_changes some text like "Password Changed".

**Comment by ares** [comment]
I'd also appreciate this

**Comment by laserlemon** [comment]
Thanks for the suggestion! I believe you'll want to add a new column to your `audits` table and define a custom Audit class that interacts with that new column on audit creation. Also, if passwords are sensitive, they should not be stored in the clear. And if they are, I don't think that storing them in audits adds any insecurity compared to storing them in the original table. I hope that makes sense! I'll close this issue but please let us know if this doesn't properly address the question. Thank you!

**Comment by ares** [comment]
I don't think this is what was asked but there's a PR that tries to solve this https://github.com/collectiveidea/audited/pull/339

**Comment by laserlemon** [comment]
Thank you, @ares!
