### ISSUE TITLE
Weird bug with db:migrate

### ISSUE THREAD

**Issue by elfassy** [collectiveidea/audited#55]
If in my users model I have:

```
acts_as_audited :except => [:firstname, :lastname, :email]
```

I can rollback and db:migrate no problem. BUT if i have

```
acts_as_audited :only => [:firstname, :lastname, :email]
```

I get
    Could not find table 'users'
(when building from scratch).
It seems like there is a problem with the :only option.... I guess i should mention that i am also using the devise gem.
Thanks!

**Comment by fdeschenes** [comment]
This is a really old issue, which unfortunately is still unresolved as of 4.2.  Rather than commenting code out, I solved the issue this way:

```ruby
class User
  audited if self.table_exists?

  ...
end
```

If/when I have more time, I'll look into adding a check and submitting a pull request.

**Comment by laserlemon** [comment]
@fdeschenes Thank you for the workaround. Yes, please submit a PR (if you haven't already). Thank you!
