### ISSUE TITLE
Dependency on Rails

### ISSUE THREAD

**Issue by denny** [collectiveidea/audited#561]
Hi; we've been using this gem in a Padrino app (with ActiveRecord), which has been fine up until now - but the latest version seems to assume it's being used in Rails, specifically with this line: https://github.com/collectiveidea/audited/blob/v4.10.0/lib/audited/audit.rb#L178

I've added this to our project for now:
```
denny@rocinante:~/code/speakout$ cat config/initializers/audited.rb 
# Set a faux Rails version for v4.10.x of audited gem
module Rails
  class VERSION
    MAJOR = 0
  end
end
```

... which seems to have got us up and running again, but I wondered if this is something you might want to handle inside your code, to maintain the possibility of using audited in a wider range of systems (without sneaky initializers) 😄

**Comment by denny** [comment]
Just adding a note that my sneaky initializer has already managed to bite me in the back, as it breaks another gem (for Payu integration) which also has a check for the presence of Rails, and changes behaviour depending on the outcome of that check.

I think my best bet here is to revert to the previous version of audited until this issue can be addressed. Let me know if there's anything I can do to help with that.

**Comment by akostadinov** [comment]
You can add a pull request to instead use `ActiveRecord::MAJOR`. I assume that would be accepted by author.
