### ISSUE TITLE
Audit.changes and Model.revision[#] inconsistent

### ISSUE THREAD

**Issue by cloeper** [collectiveidea/audited#57]
I have an employee model using acts_as_audited. When I first create the employee, the corresponding audit data and the employee revision data are congruent. However, I do not get what I expect when reviewing the audit and revision data when I do something like this:

@employee.email = "thisisnot@myemail.com"
@employee.save

I should expect that my first revision should contain the original piece of data I entered for the employee's email address. Instead I see the very first revision of the employee with the updated email address like so:

> > @employee.revision(0)
> > => Employee id: 1, email: "thisisnot@myemail.com", active: true

When I view my audit data, audit[#].changes displays the correct change for the model.

> > @audits[0].changes
> > => "--- email: email@email.com"

and

> > @audits[1].changes
> > => {"email"=>["email@email.com", "thisisnot@myemail.com"]}

So the question arises. Why doesn't @employee.revisions reflect @audits[#].changes?

**Comment by laserlemon** [comment]
Closing as I believe this is fixed. Please re-open if that's not the case. Thank you!
