### ISSUE TITLE
CI doesn't run anymore.

### ISSUE THREAD

**Issue by thomasdziedzic** [collectiveidea/audited#588]
When visiting https://travis-ci.org/github/collectiveidea/audited/builds/774273090 I see a banner at the top:

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

I just opened a PR and it looks like travis has indeed stopped running the CI for this project https://github.com/collectiveidea/audited/pull/587

**Comment by danielmorrison** [comment]
Yep, looks like I need to switch that over sometime.

**Comment by danielmorrison** [comment]
Fixed in #598. Moving to github actions.
