### ISSUE TITLE
Can you check whether methods exist before creating them?

### ISSUE THREAD

**Issue by pupeno** [collectiveidea/audited#59]
Hello,

When adding methods to another class, like the methods you add to models, can you first check whether such methods do exists and throw an exception if they do. I added auditing to a project which had some relationships called versions and it started behaving bad in very weird ways.

I think it's a good metaprogramming practice to always check for the existence of methods before adding them.

Thanks.

**Comment by laserlemon** [comment]
@pupeno, we're cleaning up some of our stale issues. Is this still an issue for you? Thank you!
