### ISSUE TITLE
Ruby 2.7.5 Issues with Audited 5

### ISSUE THREAD

**Issue by x9sim9** [collectiveidea/audited#617]
Having multiple issues with audited 5 with ruby 2.7.5

1, Circular dependency detected while autoloading constant Audit
- adding this to the initializer seems to let me progress further
- require "audited/audit"

2. Validation error on every model when saving with audits
- Error while creating MyModel - {:audits=>[{:error=>:invalid}]} -

any ideas?

thanks,
Simon

**Comment by handlez36** [comment]
@x9sim9 any luck with this one? Not sure if I'm facing the same issue, but I'm on Ruby 2.7.5 and using Audited 5, I continue to receive "Psych::BadAlias (Unknown alias: 1476)" when attempting to save an audited model.

**Comment by x9sim9** [comment]
I ended up downgrading back to version 4 which works without issue

**Comment by uberllama** [comment]
Has this been resolved in subsequent versions?

**Comment by Shazzaam** [comment]
I'm seeing this issue with 5.0.2 in Rails 7 when using a custom audit class.

**Comment by x9sim9** [comment]
My project also has an Audit class, so could be a common problem...

**Comment by danielmorrison** [comment]
I [merged an update](https://github.com/collectiveidea/audited/pull/609) that expects a string instead of a class to`config.audit_class`

I believe that will solve this issue.

**Comment by jamesmacwilliam** [comment]
for anyone else who is running into this issue on upgrade:

first move the custom audit class to it's own file, the `require "audit/audited"` in the initializer will cause an issue if you don't

then for the custom audit class, set it equal to the string representation of the class rather than the class itself as detailed in the commit above

ie:

```
config.audit_class = "CustomAudit"
```
