### ISSUE TITLE
The custom method for conditional audits cannot be a private method

### ISSUE THREAD

**Issue by mstroming** [collectiveidea/audited#640]
The documentation here gives an example of a custom method being a `private` method. That doesn't work in version 4.7.x. The method does not get called if it's `private`.

https://github.com/collectiveidea/audited/tree/v4.7.1#conditional-auditing

There are many outstanding pull requests so I decided to open an issue instead of correcting the documentation.

**Comment by danielmorrison** [comment]
Nice catch. Fixed.
