### ISSUE TITLE
audited on application-record level disturbs associated audits

### ISSUE THREAD

**Issue by chmich** [collectiveidea/audited#663]
Hi,

regarding to [associated audits](https://github.com/collectiveidea/audited#associated-audits) i have this setup for a polymorphic association and it's working well:

```
class Memo < ApplicationRecord
  belongs_to :memo_writer, polymorphic: true, required: true
  audited associated_with: :memo_writer
end

class Employee < ApplicationRecord
  audited
  has_many :memos, as: :memo_writer
  has_associated_audits
end
```
## Problem

Now i want to exclude all `created_at` and `updated_at` on application record level for the whole database:

```
class ApplicationRecord < ActiveRecord::Base
  audited except: [:created_at, :updated_at]
end
```

At the point there is placed any `audited` on the super class (ApplicationRecord) audited doesn't fillup the columns `associated_id` and `associated_type` on the audits table and associated audits are no more working.

## Suggestion

it'd be fine if there'd be the option for setting defaults that can be overriden in the model.

**Comment by danielmorrison** [comment]
Yes, `audited` isn't intended to be called multiple times that way. 

However, those particular columns also aren't meant to be audited:

https://github.com/collectiveidea/audited/blob/548cbe98c1abe07114490c923c72c233170ee6b5/lib/audited.rb#L41

Are you seeing a situation where they are getting audited?

**Comment by danielmorrison** [comment]
If you have other columns you want to exclude, you can use `non_audited_columns = [:first_name, :last_name]` in a model.

**Comment by chmich** [comment]
Thanks @danielmorrison good to know that and for me thats answered
