### ISSUE TITLE
Security Reports

### ISSUE THREAD

**Issue by htrgouvea** [collectiveidea/audited#672]
Hi folks! 

Can you enable security report functionality in this repository? I would like to send some questions and I believe they need to be kept private until final formatting.

https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

Thanks!

**Comment by htrgouvea** [comment]
Hi @danielmorrison,
I opened the report but for some reason you don't have access. The people with access are not answering me there. You can verify?

**Comment by danielmorrison** [comment]
I see it. I'm new to Github Security Advisories but am taking a look.

**Comment by htrgouvea** [comment]
If you can request a CVE for this Advisory, I would be very grateful. Thanks!
