### ISSUE TITLE
Readonly attributes are registered as modified

### ISSUE THREAD

**Issue by djpremier** [collectiveidea/audited#684]
In models that use [`attr_readonly`](https://api.rubyonrails.org/classes/ActiveRecord/ReadonlyAttributes/ClassMethods.html#method-i-attr_readonly), the specified attributes aren't modifiable after resource create, but the audit is generated regardless of the configuration and order (it registers regardless of whether [`attr_readonly`](https://api.rubyonrails.org/classes/ActiveRecord/ReadonlyAttributes/ClassMethods.html#method-i-attr_readonly) comes before or after `audited`)

Example:

```rb
class User < ApplicationRecord
  attr_readonly :email

  audited
end
```

```rb
# All rigth, this should register
user = User.create(email: "abc@example.com")
user.email # => "abc@example.com"
audit = user.audits.last
audit.action # => "create"
audit.audited_changes # => {"email"=>[nil, "abc@example.com"]}

# Bad, this shouldn't register
user.update(email: "new@example.com")
user.email # => "abc@example.com"
audit = user.audits.last
audit.action # => "update"
audit.audited_changes # => {"email"=>["abc@example.com", "new@example.com"]}
```

**Comment by sriddbs** [comment]
am happy to take this up and submit a PR
