### ISSUE TITLE
Rails 7.1.beta.1 - DEPRECATION WARNING: Module.deprecate without a deprecator is deprecated

### ISSUE THREAD

**Issue by zealot128** [collectiveidea/audited#685]
On https://github.com/collectiveidea/audited/blob/main/lib/audited.rb#L25

Like on [devise](https://github.com/heartcombo/devise/pull/5590/files), one needs to introduce a "Deprecator" base class to call the deprecations on.
Or just remove the deprecated and audited_model method and cut a new minor/major release might be an alternative, too.

**Comment by danielmorrison** [comment]
Merged. Will be released in 5.4.0 shortly.
