### ISSUE TITLE
Can't generate audits table in Oracle

### ISSUE THREAD

**Issue by gregjs** [collectiveidea/audited#75]
Seems 'comment' is a reserved word and as a result the table can't be created in an Oracle schema.  Any chance of a fix for this?

**Comment by reejosamuel** [comment]
+1 I think we could rename comment to remark

@gregjs  i have a fork i'm using for the time being https://github.com/reejosamuel/audited

`gem 'audited-activerecord', github: 'reejosamuel/audited', branch: 'rails4'`

**Comment by laserlemon** [comment]
Hi there! We’re doing some open source maintenance work and closing old issues. If this issue is still a concern, please re-open it within two weeks. Thanks!
