### ISSUE TITLE
audited_changes column does not work on  Mysql but works on M$Sql

### ISSUE THREAD

**Issue by nengine** [collectiveidea/audited#77]
I'm getting really wired error on Mysql server server 5.5.16 community edition with Rails 3.1.1, JRuby 1.6.5.  Whenever I make updates on a User model it is properly audited for all other columns but audited_changes column has wired value  '---'.  But then I switched the database to M$SQL and audited_changes has audited field and created/updated values.  Really strange..

**Comment by kennethkalmer** [comment]
@nengine apologies for letting this hang so long... Any feedback to share on the issue? Did you get it working on MySQL?

**Comment by laserlemon** [comment]
Hi there! We’re doing some open source maintenance work and closing old issues. If this issue is still a concern, please re-open it within two weeks. Thanks!
