### ISSUE TITLE
Is it possible to associate a audit with a parent_id?

### ISSUE THREAD

**Issue by marcalc** [collectiveidea/audited#84]
Is it possible to group all the associated audits with a single parent_id?

For example, I'm saving a Role, which has many Permissions. I'd like to see when a role is updated, all the "child" audits for the associated permissions.

Is it? 

Thanks

Marcos

**Comment by kennethkalmer** [comment]
@marcalc apologies for letting this hang around so long. You can use the [associated audits](https://github.com/collectiveidea/audited#associated-audits) feature to achieve this.
