### ISSUE TITLE
Username is nil in Audit

### ISSUE THREAD

**Issue by usammmy** [collectiveidea/audited#86]
I am trying to audit a model called Student but when I look at records in Audit, username is always nil. Any ideas?

class Student < ActiveRecord::Base
  acts_as_audited 
end  

Audit.all =>{ < Audit id: 1, auditable_id: 5001, auditable_type: "Student", associated_id: nil, associated_type: nil, user_id: 1, user_type: "User", username: nil, action: "update", audited_changes: {"name"=>["foo-bar", "test"]}, version: 1, comment: nil, remote_address: "127.0.0.1", created_at: "2012-02-13 18:10:55">}

**Comment by kennethkalmer** [comment]
@cindyward1 you could just have a helper method that returns the email address and hook it up like this:

```ruby
class ApplicationController < ActionController::Base
  # ...
  private
  def current_employee_email
    current_employee.email
  end
end

Audited.current_user_method = :current_employee_email
```

**Comment by ultrawebmarketing** [comment]
Anyone visiting in the future from Google. You can accomplish this by using a [Custom Audit](https://github.com/collectiveidea/audited#custom-audit-model). Just following the documentation and then add an after_save hook to set the username using update_columns. You can also use this trick to add columns to the audit table. In my case I am using audit in a multi-tenant application, so I added an account_id column to the table. Here is how I did it

```
# app/models/custom_auditor.rb
class CustomAuditor < Audited::Audit
  after_save :log_additional_information
  
  private

  def log_additional_information
    # your model automatically as a belong_to association to your User model
    # I use update_columns so it updates the database directly bypassing callbacks and validations
    # not only am I storing the username of the user, I'm also storing the associated account for the user
    self.update_columns(username: self.user.fullname, account_id: self.user.account_id)
  end

end
```

```
#config/initializers/audit.rb
Audited.config do |config|
  config.audit_class = CustomAuditor
end
```
