### ISSUE TITLE
Rails 3.2 undefined method `class_inheritable_reader'

### ISSUE THREAD

**Issue by tobyhede** [collectiveidea/audited#88]
class_inheritable_reader has been removed in Rails 3.2. 

On startup:

    `method_missing': undefined method `class_inheritable_reader' for #<Class:0x007fa55c621bd8> (NoMethodError)
    /acts_as_audited-2.0.0.rc7/lib/acts_as_audited/auditor.rb:55:in `acts_as_audited'

**Comment by kennethkalmer** [comment]
Apologies for having this lie here so long, I'm closing this since we're no longer support Rails 3.x. If this is still an issue, kindly provide a PR against the 3.0-stable branch.
