### ISSUE TITLE
Conflict with acts_as_paranoid/paranoia

### ISSUE THREAD

**Issue by gerald** [collectiveidea/audited#89]
Is there a known conflict with acts_as_paranoid? I'm using both of them in the app and I find that I get an "You cannot call create unless the parent is saved" error when I use acts_as_paranoid along with acts_as_audited.

Thanks.

**Comment by laserlemon** [comment]
Hi there! We’re doing some open source maintenance work and closing old issues. If this issue is still a concern, please re-open it within two weeks. Thanks!
