### ISSUE TITLE
How can i use multiple :associated_with

### ISSUE THREAD

**Issue by tonymarschall** [collectiveidea/audited#92]
I tried to setup associated_with with multiple associations. This does not work. 

From the readme:

```
class User < ActiveRecord::Base
  acts_as_audited :associated_with => :company
end
```

What i have tried:

```
class User < ActiveRecord::Base
  acts_as_audited :associated_with => [:company, :projects]
end
```

**Comment by laserlemon** [comment]
Thank you! Unfortunately, this isn't going to be possible out of the box. Each audit stores a single foreign key to track the associated "parent" but supporting an arbitrary number of parents would require a significant data model change. You might be able to accomplish this with some tweaks to your own schema and using a custom Audit class. I hope that helps and thank you for the issue!
