### ISSUE TITLE
Whitelist attributes breaks the gem

### ISSUE THREAD

**Issue by ghost** [collectiveidea/audited#93]
If you turn on whitelisting attributes in the application config, because Audit is an AR class, it applies to that too.

The error I get is
Can't mass-assign protected attributes: action, audited_changes, comment

**Comment by kennethkalmer** [comment]
Please continue the discussion in #186 if this is still relevant to you. Like I mentioned there, I'm worried that having `action` & `audited_changes` accessible for mass-assignment allows malicious users to easily tamper with the audits and thus render them useless...
