### ISSUE TITLE
Autiting causes ruby process to use excessive amount of memory

### ISSUE THREAD

**Issue by achivetta** [collectiveidea/audited#95]
I have a migration that touches a lot of audited records.  When I ran it without disabling auditing it used almost 700MB of memory.  If I disabled auditing (by calling the without_auditing method), that dropped to 70MB.  It would seem that acts_as_audited leaks memory (or causes Rails to leak memory) in some way.

**Comment by laserlemon** [comment]
Thank you! Closing in favor of #118.
